name: 'Run Python Tests'
description: 'Run the standard gstlearn Python test suite'
runs:
  using: "composite"
  steps:

    - name: Test installed Python package
      shell: bash
      run: |
        python -c 'import gstlearn as gl; gl.acknowledge_gstlearn()'
        python tests/py/test_Arguments.py
        python tests/py/test_Assessors.py
        python tests/py/test_Matrix.py
        python tests/py/test_h5.py
