# Generated by CMake

if("${CMAKE_MAJOR_VERSION}.${CMAKE_MINOR_VERSION}" LESS 2.8)
   message(FATAL_ERROR "CMake >= 2.8.3 required")
endif()
if(CMAKE_VERSION VERSION_LESS "2.8.3")
   message(FATAL_ERROR "CMake >= 2.8.3 required")
endif()
cmake_policy(PUSH)
cmake_policy(VERSION 2.8.3...3.29)
#----------------------------------------------------------------
# Generated CMake target import file.
#----------------------------------------------------------------

# Commands may need to know the format version.
set(CMAKE_IMPORT_FILE_VERSION 1)

# Protect against multiple inclusion, which would fail when already imported targets are added once more.
set(_cmake_targets_defined "")
set(_cmake_targets_not_defined "")
set(_cmake_expected_targets "")
foreach(_cmake_expected_target IN ITEMS gstlearn::gmtsph gstlearn::shared gstlearn::static)
  list(APPEND _cmake_expected_targets "${_cmake_expected_target}")
  if(TARGET "${_cmake_expected_target}")
    list(APPEND _cmake_targets_defined "${_cmake_expected_target}")
  else()
    list(APPEND _cmake_targets_not_defined "${_cmake_expected_target}")
  endif()
endforeach()
unset(_cmake_expected_target)
if(_cmake_targets_defined STREQUAL _cmake_expected_targets)
  unset(_cmake_targets_defined)
  unset(_cmake_targets_not_defined)
  unset(_cmake_expected_targets)
  unset(CMAKE_IMPORT_FILE_VERSION)
  cmake_policy(POP)
  return()
endif()
if(NOT _cmake_targets_defined STREQUAL "")
  string(REPLACE ";" ", " _cmake_targets_defined_text "${_cmake_targets_defined}")
  string(REPLACE ";" ", " _cmake_targets_not_defined_text "${_cmake_targets_not_defined}")
  message(FATAL_ERROR "Some (but not all) targets in this export set were already defined.\nTargets Defined: ${_cmake_targets_defined_text}\nTargets not yet defined: ${_cmake_targets_not_defined_text}\n")
endif()
unset(_cmake_targets_defined)
unset(_cmake_targets_not_defined)
unset(_cmake_expected_targets)


# Create imported target gstlearn::gmtsph
add_library(gstlearn::gmtsph STATIC IMPORTED)

set_target_properties(gstlearn::gmtsph PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "/home/runner/work/gstlearn/gstlearn/3rd-party/gmtsph/"
)

# Create imported target gstlearn::shared
add_library(gstlearn::shared SHARED IMPORTED)

set_target_properties(gstlearn::shared PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "/home/runner/work/gstlearn/gstlearn/include/;/home/runner/work/gstlearn/gstlearn/_codeql_build_dir"
  INTERFACE_LINK_LIBRARIES "Eigen3::Eigen"
)

# Create imported target gstlearn::static
add_library(gstlearn::static STATIC IMPORTED)

set_target_properties(gstlearn::static PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "/home/runner/work/gstlearn/gstlearn/include/;/home/runner/work/gstlearn/gstlearn/_codeql_build_dir"
  INTERFACE_LINK_LIBRARIES "\$<LINK_ONLY:OpenMP::OpenMP_CXX>;\$<LINK_ONLY:gstlearn::gmtsph>;Eigen3::Eigen;\$<LINK_ONLY:Boost::boost>;\$<LINK_ONLY:NLopt::nlopt>;/usr/lib/x86_64-linux-gnu/hdf5/serial/libhdf5.so;/usr/lib/x86_64-linux-gnu/libcrypto.so;/usr/lib/x86_64-linux-gnu/libcurl.so;/usr/lib/x86_64-linux-gnu/libpthread.a;/usr/lib/x86_64-linux-gnu/libsz.so;/usr/lib/x86_64-linux-gnu/libz.so;/usr/lib/x86_64-linux-gnu/libdl.a;/usr/lib/x86_64-linux-gnu/libm.so;/usr/lib/x86_64-linux-gnu/hdf5/serial/libhdf5_cpp.so;/usr/lib/x86_64-linux-gnu/hdf5/serial/libhdf5.so;/usr/lib/x86_64-linux-gnu/libcrypto.so;/usr/lib/x86_64-linux-gnu/libcurl.so;/usr/lib/x86_64-linux-gnu/libpthread.a;/usr/lib/x86_64-linux-gnu/libsz.so;/usr/lib/x86_64-linux-gnu/libz.so;/usr/lib/x86_64-linux-gnu/libdl.a;/usr/lib/x86_64-linux-gnu/libm.so"
)

# Import target "gstlearn::gmtsph" for configuration "Release"
set_property(TARGET gstlearn::gmtsph APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(gstlearn::gmtsph PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE "CXX"
  IMPORTED_LOCATION_RELEASE "/home/runner/work/gstlearn/gstlearn/_codeql_build_dir/3rd-party/gmtsph/libgmtsph.a"
  )

# Import target "gstlearn::shared" for configuration "Release"
set_property(TARGET gstlearn::shared APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(gstlearn::shared PROPERTIES
  IMPORTED_LINK_DEPENDENT_LIBRARIES_RELEASE "NLopt::nlopt"
  IMPORTED_LOCATION_RELEASE "/home/runner/work/gstlearn/gstlearn/_codeql_build_dir/Release/libgstlearn.so.1.10.0a2"
  IMPORTED_SONAME_RELEASE "libgstlearn.so.1"
  )

# Import target "gstlearn::static" for configuration "Release"
set_property(TARGET gstlearn::static APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(gstlearn::static PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE "CXX"
  IMPORTED_LOCATION_RELEASE "/home/runner/work/gstlearn/gstlearn/_codeql_build_dir/Release/libgstlearn.a"
  )

# This file does not depend on other imported targets which have
# been exported from the same project but in a separate export set.

# Commands beyond this point should not need to know the version.
set(CMAKE_IMPORT_FILE_VERSION)
cmake_policy(POP)
