#!/bin/csh -f

# This script is meant to update the reference output file starting from the resulting test file output file Release mode only)
# 

# Reference directory
set command_location = `dirname $0`
set DIR = $command_location/../..

set nargs = $#argv
if ($nargs < 2) then
		echo "Update the reference output file from the build test output file (Release mode only)"
		echo "Syntax:"
		echo "update_test name1 nametest"
		echo "   name1    : Name of the subContainer (e.g.: data, ipynb, py, r, rmd, cpp)"
		echo "   nametest : Name of the test (e.g.: Jeu1, Tuto_Plot2D, Hermite, etc...)"
		exit
endif

set name1 = $argv[1]
set nametest = $argv[2]
set option = "Release"

if ($name1 == "data") then
		set directref = $nametest
		set directest = $nametest
		set directaux = $nametest
		set nameref = "Result.ref"
		set namecmp = "Result.out"
endif
if ($name1 == "cpp") then
		set directref = "output"
		set directest = ""
		set directaux = "myoutput"
		set nametest = `basename $nametest .cpp`
		set nameref = $nametest.ref
		set namecmp = $nametest.out
endif
if ($name1 == "py") then
		set directref = "output"
		set directest = ""
		set directaux = "myoutput"
		set nametest = `basename $nametest .py`
		set nameref = $nametest.ref
		set namecmp = $nametest.out
endif
if ($name1 == "r") then
		set directref = "output"
		set directest = ""
		set directaux = "myoutput"
		set nametest = `basename $nametest .r`
		set nameref = $nametest.ref
		set namecmp = $nametest.out
endif
if ($name1 == "ipynb") then
		set directref = "output"
		set directest = ""
		set directaux = "myoutput"
		set nametest = `basename $nametest .ipynb`
		set nameref = $nametest.asciidoc
		set namecmp = $nametest.asciidoc
endif
if ($name1 == "rmd") then
		set directref = "output"
		set directest = ""
		set directaux = "myoutput"
		set nametest = `basename $nametest .Rmd`
		set nameref = $nametest.out
		set namecmp = $nametest.out
endif

set FILEREF = $DIR/tests/$name1/$directref/$nameref
set FILEAUX = $DIR/tests/$name1/$directaux/$nameref
set FILETMP = $FILEREF
if (-e $FILEAUX) then
	set FILETMP = $FILEAUX
	echo ">>> Using non-standard reference for :" $nameref
endif
echo $FILETMP

set FILECMP = $DIR/build/tests/$name1/$option/$directest/$namecmp

cp $FILECMP $FILETMP
