from os import name

project = "gstlearn"

copyright = ""
author = ""

extensions = [
    "sphinx.ext.autodoc",
    "sphinx.ext.napoleon",
    "sphinx.ext.mathjax",
    "sphinx.ext.autosummary",
    "myst_parser",
]

html_theme = "sphinx_rtd_theme"

autodoc_default_options = {
    "members": True,
    "undoc-members": True,
    "inherited-members": True,
}

napoleon_google_docstring = True
napoleon_numpy_docstring = True
napoleon_use_ivar = True
napoleon_use_param = False
autosummary_generate = True

suppress_warnings = ["autodoc", "docutils"]


# fmt: off
def autodoc_skip_member_handler(app, what, name, obj, skip, options):
    short_name = name.split(".")[-1]

    if short_name == "thisown":
        return True

    if short_name.startswith("E_"):
        return True

    functions_to_skip = [
        "identifyNames",
        "unique",
        "flatten",
        "resetFromCSV",
        "simulateBernoulli",
        "getNames",
        "deleteColumnsByLocator",
        "cumulateInPlace",
        "setNameByColIdx",
        "getCenters",
        "dumpNNZ",
        "compress",
        "expandNameList",
        "truncateDigitsInPlace",
        "qnormVec",
        "isSorted",
        "normalizeFromGaussianDistribution",
        "getColumnsByColIdxInterval",
        "whereMaximum",
        "deleteColumnByColIdx",
        "getExtensionInPlace",
        "getMostSignificant",
        "capInPlace",
        "sortRanks",
        "getNameByLocator",
        "createFromSamples",
        "getExtension",
        "dumpStats",
        "sequenceInPlace",
        "getColumnsAsVVD",
        "complement",
        "resetFromSamples",
        "getAllColumns",
        "isUIDValid",
        "setArgVectorInt",
        "morpho_opening",
        "getColumnByLocator",
        "morpho_double2image",
        "concatenateInPlace",
        "suppressTest",
        "getMaximum",
        "createFromCSV",
        "addInPlace",
        "simulateGaussian",
        "concatenate",
        "resetFromOnePoint",
        "getCoorMaximum",
        "createFromNF",
        "normalize",
        "getMean",
        "getArgVectorInt",
        "innerProduct",
        "cumsum",
        "initVDouble",
        "setName",
        "getColumn",
        "sortInPlace",
        "getExtrema",
        "whereMinimum",
        "getArgInt",
        "isSampleIndexValid",
        "isEqualExtended",
        "simulateInteger",
        "getNamesByLocator",
        "pnormVec",
        "getNamesByUID",
        "isSampleIndicesValid",
        "getExtensionDiagonal",
        "isLocatorIndexValid",
        "createEmpty",
        "getColumnsByColIdx",
        "resetFromBox",
        "sequence",
        "addCst",
        "simulateGaussianInPlace",
        "getMinimum",
        "linearCombinationInPlace",
        "resetReduce",
        "getArgVectorDouble",
        "normalScore",
        "getSimvar",
        "deleteColumnByUID",
        "getVariance",
        "gridcell_neigh",
        "truncateDecimalsInPlace",
        "getLocVariable",
        "crossProduct3DInPlace",
        "morpho_image2double",
        "createFromOnePoint",
        "getNameByUID",
        "whereElement",
        "orderRanks",
        "reorder",
        "arrangeInPlace",
        "rangeVals",
        "morpho_duplicate",
        "initVVDouble",
        "addSquareInPlace",
        "quantiles",
        "hasLocVariable",
        "setSimvar",
        "createFromBox",
        "cumulate",
        "setArgVectorDouble",
        "fillUndef",
        "linearCombinationVVDInPlace",
        "deleteColumnsByUID",
        "setLocVariable",
        "sample",
        "getColumnByColIdx",
        "reduce",
        "setArgInt",
        "isIsotropic",
        "flattenInPlace",
        "morpho_labelsize",
        "getColumnByUID",
        "getAllNames",
        "morpho_closing",
        "getStdv",
        "mean1AndMean2ToStdev",
        "crossProduct3D",
        "normalizeCodir",
        "sequenceVD",
        "morpho_dilation",
        "createReduce",
        "filter",
        "isEqual",
        "initVInt",
        "create",
        "initVVInt",
        "cumulIncrement",
        "extensionDiagonal",
        "createFillRandom",
        "initVString",
        "resetSamplingDb",
        "copy",
        "getColumnsByLocator",
        "updLocVariable",
        "extractInPlace",
        "updSimvar",
        "cumulLog",
        "unflattenInPlace",
        "getExtends",
        "getColumnsByUIDInterval",
        "getCenter",
        "morpho_union",
        "getColumnsByUID",
        "simulateBoolean",
        "sort",
        "transformVD",
        "squeezeAndStretchInPlaceForward",
        "getColumnsAsMatrix",
        "getColumnsActiveAndDefined",
        "capInPlaceVVD",
        "count",
        "simulateUniform",
        "revert",
        "getCoorMinimum",
        "initThread",
        "setNameByUID",
        "deleteColumnsByColIdx",
        "power",
        "isInList",
        "getNamesByColIdx",
        "isDimensionIndexValid",
        "getExtremas",
        "createSamplingDb",
        "createFromDbGrid",
        "getRange",
        "getName",
        "squeezeAndStretchInPlaceBackward",
        "getNameByColIdx",
        "unflatten",
        "reduceOne",
        "getCorrelation",
        "inverse",
        "getColumns",
        "setNameByLocator",
        "mergeInPlace",
        "sampleRanks",
        "multiplyComplexInPlace",
        "deleteColumnsByUIDRange",
        "addMultiplyConstantInPlace",
        "morpho_negation",
        "dumpRange",
        "createFromGridRandomized",
        "resetFromGridRandomized",
        "deleteColumns",
    ]
    if name in functions_to_skip:
        return True
    return skip


# fmt: on


def setup(app):
    app.connect("autodoc-skip-member", autodoc_skip_member_handler)
