name: install-boost-windows
description: "Install the Boost headers under windows"
author: 'Fabien Ors'

inputs:
  boost-root:
    description: 'Boost installation directory'
  boost-version:
    description: 'Boost version to be installed'
    default: "1.72.0"

runs:
  using: "composite"
  steps:
  - uses: actions/checkout@v3
  
  - name : Download and uncompressed Boost headers
    shell: powershell
    run: |
      $BOOST_VERSION="${{inputs.boost-version}}" -replace '\.','_'
      $BOOST_URL="https://netix.dl.sourceforge.net/project/boost/boost/${{inputs.boost-version}}/boost_$BOOST_VERSION.tar.bz2"
      mkdir ${{inputs.boost-root}}
      Invoke-WebRequest -Uri "$BOOST_URL" -OutFile ${{inputs.boost-root}}/download.tar.bz2
      7z -o${{inputs.boost-root}} x ${{inputs.boost-root}}/download.tar.bz2 -y -bd
      7z -o${{inputs.boost-root}} x ${{inputs.boost-root}}/download.tar -y -bd
      pwd
      ls
      cd ${{inputs.boost-root}}
      pwd
      ls
      cd boost*
      pwd
      ls
      cd boost
      pwd
      ls
