---
title: "Latex interface"
output:
  pdf_document: default
  html_document: default
date: "2025-09-23"
editor_options:
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
rm(list=ls())
library(gstlearn)
library(htmltools)
```

This script is meant to demonstrate the use of the LateX interface functions.

### Dense matrices

A Dense matrix is generated with random values

```{r}
neq = 5
matrix = MatrixDense_createFillRandom(neq, neq)
err = matrix$display()
```

```{r, results='asis'}
a = matrix$toLatex()
cat(a)
```

### Sparse matrices

### Sparse matrices

A Sparse matrix is generated with random values

```{r}
neq       = 5
matrix = MatrixSparse_createFillRandom(neq, neq, 0.2)
matrix$display()
```

```{r, results='asis'}
a = matrix$toLatex()
cat(a)
```

### Tables

A Table is generated by storing the statistics calculated on an input Db.

```{r}
mydb = Db_createFillRandom(100, 2, 3)
table = mydb$displayStats()
table$display()
```


```{r, results='asis'}
a = table$toLatex()
cat(a)
```
