---
title: "Tutorial Grids"
author: "D. Renard"
date: "25 juin 2022"
output:
  pdf_document: default
  html_document: default
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
rm(list=ls())
library(gstlearn)
library(ggplot2)
library(ggpubr)
```

# Standard Grid

We construct a standard non rotated 2-D grid 

```{r}
grid = DbGrid_create(nx=c(14,7),dx=c(1.,1.5), x0=c(100,200))
uid = grid$addColumns(VectorHelper_simulateUniform(grid$getSampleNumber()),radix="var")
grid
```

Displaying the grid cells

```{r}
plot.grid(grid,title="Display of Regular Grid")
```

Displaying the grid nodes only

```{r}
plot.point(grid,color_name="var",title="Display of Grid Nodes",show.legend.color = TRUE)
```

# Rotated grid

```{r}
grid = DbGrid_create(nx=c(14,7),dx=c(1.,1.5), x0=c(100,200), angles=c(30,0))
uid = grid$addColumns(VectorHelper_simulateUniform(grid$getSampleNumber()),radix="var")
grid
```

Displaying the cells

```{r}
plot.grid(grid,title="Display of Rotated Grid")
```

As a set of grid nodes

```{r}
plot.point(grid,color_name="var",title="Display of Rotated Grid Nodes",
           show.legend.color = TRUE)
```

