name: 'Run R Tests'
description: 'Run the standard gstlearn R test suite'
runs:
  using: "composite"
  steps:

    - name: Test installed R package
      shell: bash
      run: |
        Rscript -e "library('gstlearn'); acknowledge_gstlearn()"
        Rscript tests/r/test_Arguments.R
        Rscript tests/r/test_Assessors.R
        Rscript tests/r/test_Matrix.R
        Rscript tests/r/test_dumpToNF.R
