---
title: "Introduction"
output: html_document
date: '2023-09-02'
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

In this document, you will find the list of the different files which will be browsed during this course as well as a short description.

# Global presentation

What is **gstlearn**?

- Discover the web site
- Documentation (Application Programming Interface, Tutorials)
- Road Map (Stable version vs. Version under development). Github site
- Internal organization: C++, R, Python (accessor, graphics, ...)
- Some important features:
  . Object language
  . Processing through SWIG
  . Memory and garbage collector
  . Adapting documentation (built using Doxygen from C++)
- How to install it (Rstudio, Jupyter-notebook, Terminal)

# Overview of Geostatistics

The principle is to browse the different steps of a standard geostatistical study.

### Get familiar with the library

The contents of this paragraph is described in the [**Tutorial for Db**](./02_Db.Rmd).

1. Download Data Sets (using URL): we will use the 2D Scotland files.

- Pay attention on the language and platform specifics
- Other importing format (CSV, Panda Frame, Neutral File)
- Various features for accessing data
- Unique name for variables
- Discussion on *locators*
- Particular file organization (Grid)

2. Basic operations using a (numerical) Data Base (Db)

- Adding and suppressing one or several variable(s)
- Masking samples using selection (only keep inshore information)
  
3. Basic statistics

- Summarize basic statistics as a table
- Show (C++) documentation (interpretation of Doxygen information)

### Basic Geostatistics

1. Variography

- The contents of this chapter is described in the [**Tutorial for Variography**](./04_Variography.Rmd)
- Variogram cloud
- Experimental variogram: isotropic and directional variogram
- Fitting a Model: automatic version, selecting basic structures, with constraints ,...
- Variogram maps
  
2. Estimation using Kriging

- The contents of this chapter is described in the [**Tutorial for Estimation**](./05_Kriging.Rmd)
- Simple Kriging
- Ordinary Kriging (adding Universality condition)
- Produce maps for estimation and standard deviation of the estimation errors
- Neighborhood definition (unique, moving, possibility to introduce faults)
- Cross-validation (K-Fold option)
  
3. Simulations

- The contents of this chapter is described in the [**Tutorial for Simulations**](./07_Simulations.Rmd)
- Using Turning Bands method
- Non-conditional or conditioning to data
  
4. Multivariate case

- The contents of this chapter is described in the [**Tutorial for Multivariate**](./06_Multivariate.Rmd)
- Define several target variables simultaneously and re-run previous steps
- Simple and cross-variograms
- Coiging

# Advanced usage

How to turn **gstlearn** for personal usage?
 
- Object principle (heritage)
- Example: enhance one capability of Moving Neighborhood search
 
# Quick overview of SPDE

- Some theory (meshing, precision matrix, sparse matrix)
- Using API for performing estimation and  somulations
- Highlighting the non-stationarity: variable anisotropy
- Working in different spaces: on the sphere

