name: install-eigen-windows
description: "Install the Eigen3 headers under windows"
author: 'Fabien Ors'

inputs:
  boost-root:
    description: 'Eigen installation directory'
  boost-version:
    description: 'Eigen version to be installed'
    default: "3.4.0"

runs:
  using: "composite"
  steps:
  - uses: actions/checkout@v3

  - name : Download, uncompressed and install Eigen headers
    shell: powershell
    run: |
      $EIGEN_URL="https://gitlab.com/libeigen/eigen/-/archive/${{inputs.eigen-version}}/eigen-${{inputs.eigen-version}}.zip"
      mkdir eigen_src
      curl --progress-bar --location --output eigen_src/download.zip $EIGEN_URL
      7z -oeigen_src x eigen_src/download.zip -y -bd
      cd eigen_src && cp -r eigen-*/* .
      mkdir build
      cmake -Bbuild -DCMAKE_INSTALL_PREFIX="${{inputs.eigen-root}}"
      cmake --build build --target install
