# Why is cmake file GLOB evil?
# https://stackoverflow.com/questions/32411963/why-is-cmake-file-glob-evil
set(INCS
  geoslib_d.h
  geoslib_define.h
  geoslib_enum.h
  geoslib_f.h
  geoslib_f_private.h
  geoslib_old_f.h
  Anamorphosis/AAnam.hpp
  Anamorphosis/AnamContinuous.hpp
  Anamorphosis/AnamDiscrete.hpp
  Anamorphosis/AnamDiscreteDD.hpp
  Anamorphosis/AnamDiscreteIR.hpp
  Anamorphosis/AnamEmpirical.hpp
  Anamorphosis/AnamHermite.hpp
  Anamorphosis/AnamUser.hpp
  Anamorphosis/CalcAnamTransform.hpp
  Anamorphosis/PPMT.hpp
  API/PGSSPDE.hpp
  API/SPDE.hpp
  API/SPDEParam.hpp
  API/Style.hpp
  API/TestInheritance.hpp
  Arrays/AArray.hpp
  Arrays/Array.hpp
  Arrays/BImage.hpp
  Arrays/BImageStringFormat.hpp
  Basic/AException.hpp
  Basic/AFunction.hpp
  Basic/AFunctional.hpp
  Basic/ArgumentTest.hpp
  Basic/ASerializable.hpp
  Basic/AStringable.hpp
  Basic/AStringFormat.hpp
  Basic/CSVformat.hpp
  Basic/FFT.hpp
  Basic/File.hpp
  Basic/FunctionalSpirale.hpp
  Basic/GlobalEnvironment.hpp
  Basic/Grid.hpp
  Basic/HDF5format.hpp
  Basic/ICloneable.hpp
  Basic/Indirection.hpp
  Basic/Interval.hpp
  Basic/Law.hpp
  Basic/Limits.hpp
  Basic/MathFunc.hpp
  Basic/Memory.hpp
  Basic/NamingConvention.hpp
  Basic/OptCst.hpp
  Basic/OptCustom.hpp
  Basic/OptDbg.hpp
  Basic/Plane.hpp
  Basic/PolyLine2D.hpp
  Basic/RepeatMacro.hpp
  Basic/RepeatMacroOrig.hpp
  Basic/RepeatMacroSwig.hpp
  Basic/String.hpp
  Basic/Tensor.hpp
  Basic/Timer.hpp
  Basic/Utilities.hpp
  Basic/VectorHelper.hpp
  Basic/VectorNumT.hpp
  Basic/VectorT.hpp
  Basic/WarningMacro.hpp
  Boolean/AShape.hpp
  Boolean/ModelBoolean.hpp
  Boolean/ShapeEllipsoid.hpp
  Boolean/ShapeHalfEllipsoid.hpp
  Boolean/ShapeHalfParaboloid.hpp
  Boolean/ShapeHalfSinusoid.hpp
  Boolean/ShapeParaboloid.hpp
  Boolean/ShapeParallelepiped.hpp
  Boolean/ShapeParameter.hpp
  Calculators/ACalcDbToDb.hpp
  Calculators/ACalcDbVarCreator.hpp
  Calculators/ACalcInterpolator.hpp
  Calculators/ACalculator.hpp
  Calculators/CalcGridToGrid.hpp
  Calculators/CalcMigrate.hpp
  Calculators/CalcSimuPost.hpp
  Calculators/CalcSimuPostDemo.hpp
  Calculators/CalcSimuPostPropByLayer.hpp
  Calculators/CalcStatistics.hpp
  Covariances/ACov.hpp
  Covariances/ACovAnisoList.hpp
  Covariances/ACovFunc.hpp
  Covariances/ACovGradient.hpp
  Covariances/CovAniso.hpp
  Covariances/CovBesselJ.hpp
  Covariances/CovBesselK.hpp
  Covariances/CovCalcMode.hpp
  Covariances/CovCauchy.hpp
  Covariances/CovContext.hpp
  Covariances/CovCosExp.hpp
  Covariances/CovCosinus.hpp
  Covariances/CovCubic.hpp
  Covariances/CovDiffusionAdvection.hpp
  Covariances/CovExponential.hpp
  Covariances/CovFactory.hpp
  Covariances/CovGamma.hpp
  Covariances/CovGaussian.hpp
  Covariances/CovGC1.hpp
  Covariances/CovGC3.hpp
  Covariances/CovGC5.hpp
  Covariances/CovGCspline.hpp
  Covariances/CovGCspline2.hpp
  Covariances/CovGeometric.hpp
  Covariances/CovGradientFunctional.hpp
  Covariances/CovGradientNumerical.hpp
  Covariances/CovHelper.hpp
  Covariances/CovLinear.hpp
  Covariances/CovLinearSph.hpp
  Covariances/CovLMC.hpp
  Covariances/CovLMCAnamorphosis.hpp
  Covariances/CovLMCConvolution.hpp
  Covariances/CovLMCTapering.hpp
  Covariances/CovLMGradient.hpp
  Covariances/CovMarkov.hpp
  Covariances/CovNugget.hpp
  Covariances/CovPenta.hpp
  Covariances/CovPoisson.hpp
  Covariances/CovPower.hpp
  Covariances/CovReg1D.hpp
  Covariances/CovSincard.hpp
  Covariances/CovSpherical.hpp
  Covariances/CovStable.hpp
  Covariances/CovStorkey.hpp
  Covariances/CovTriangle.hpp
  Covariances/CovWendland0.hpp
  Covariances/CovWendland1.hpp
  Covariances/CovWendland2.hpp
  Db/Db.hpp
  Db/DbGrid.hpp
  Db/DbHelper.hpp
  Db/DbStringFormat.hpp
  Db/PtrGeos.hpp
  Drifts/ADrift.hpp
  Drifts/DriftF.hpp
  Drifts/DriftFactory.hpp
  Drifts/DriftList.hpp
  Drifts/DriftM.hpp
  Enum/AEnum.hpp
  Enum/EAnam.hpp
  Enum/ECalcMember.hpp
  Enum/ECalcVario.hpp
  Enum/EConsElem.hpp
  Enum/EConsType.hpp
  Enum/EConvDir.hpp
  Enum/EConvType.hpp
  Enum/ECov.hpp
  Enum/ECst.hpp
  Enum/EDbg.hpp
  Enum/EDirGen.hpp
  Enum/EGaussInv.hpp
  Enum/EJustify.hpp
  Enum/EKrigOpt.hpp
  Enum/ELaw.hpp
  Enum/ELoadBy.hpp
  Enum/ELoc.hpp
  Enum/EModelProperty.hpp
  Enum/EMorpho.hpp
  Enum/ENeigh.hpp
  Enum/EOperator.hpp
  Enum/EPostStat.hpp
  Enum/EPostUpscale.hpp
  Enum/EPowerPT.hpp
  Enum/EProcessOper.hpp
  Enum/ERotation.hpp
  Enum/ERule.hpp
  Enum/ESelectivity.hpp
  Enum/EShape.hpp
  Enum/ESpaceType.hpp
  Enum/ESPDECalcMode.hpp
  Enum/EStatOption.hpp
  Enum/ETape.hpp
  Estimation/CalcGlobal.hpp
  Estimation/CalcImage.hpp
  Estimation/CalcKriging.hpp
  Estimation/CalcKrigingFactors.hpp
  Estimation/CalcSimpleInterpolation.hpp
  Estimation/KrigingSystem.hpp
  Faults/Faults.hpp
  Fractures/FracDesc.hpp
  Fractures/FracEnviron.hpp
  Fractures/FracFamily.hpp
  Fractures/FracFault.hpp
  Fractures/FracList.hpp
  Geometry/ABiTargetCheck.hpp
  Geometry/BiTargetCheckBench.hpp
  Geometry/BiTargetCheckCell.hpp
  Geometry/BiTargetCheckCode.hpp
  Geometry/BiTargetCheckDate.hpp
  Geometry/BiTargetCheckDistance.hpp
  Geometry/BiTargetCheckFaults.hpp
  Geometry/BiTargetCheckGeometry.hpp
  Geometry/GeometryHelper.hpp
  Geometry/Rotation.hpp
  Gibbs/AGibbs.hpp
  Gibbs/GibbsFactory.hpp
  Gibbs/GibbsMMulti.hpp
  Gibbs/GibbsMulti.hpp
  Gibbs/GibbsMultiMono.hpp
  Gibbs/GibbsUMulti.hpp
  Gibbs/GibbsUMultiMono.hpp
  Gibbs/GibbsUPropMono.hpp
  LinearOp/ALinearOp.hpp
  LinearOp/ALinearOpMulti.hpp
  LinearOp/CGParam.hpp
  LinearOp/Cholesky.hpp
  LinearOp/HessianOp.hpp
  LinearOp/Identity.hpp
  LinearOp/IOptimCost.hpp
  LinearOp/IProjMatrix.hpp
  LinearOp/LogStats.hpp
  LinearOp/OptimCostBinary.hpp
  LinearOp/OptimCostColored.hpp
  LinearOp/PrecisionOp.hpp
  LinearOp/PrecisionOpCs.hpp
  LinearOp/PrecisionOpMultiConditional.hpp
  LinearOp/PrecisionOpMultiConditionalCs.hpp
  LinearOp/ProdMatVect.hpp
  LinearOp/ProjConvolution.hpp
  LinearOp/ProjMatrix.hpp
  LinearOp/ShiftOpCs.hpp
  LinearOp/TurboOptimizer.hpp
  LithoRule/Node.hpp
  LithoRule/PropDef.hpp
  LithoRule/Rule.hpp
  LithoRule/RuleProp.hpp
  LithoRule/RuleShadow.hpp
  LithoRule/RuleShift.hpp
  LithoRule/RuleStringFormat.hpp
  Matrix/AMatrix.hpp
  Matrix/AMatrixDense.hpp
  Matrix/AMatrixSquare.hpp
  Matrix/LinkMatrixSparse.hpp
  Matrix/MatrixFactory.hpp
  Matrix/MatrixInt.hpp
  Matrix/MatrixRectangular.hpp
  Matrix/MatrixSparse.hpp
  Matrix/MatrixSquareGeneral.hpp
  Matrix/MatrixSquareSymmetric.hpp
  Matrix/NF_Triplet.hpp
  Matrix/Table.hpp
  Mesh/AMesh.hpp
  Mesh/LinkSphTriangle.hpp
  Mesh/MeshEStandard.hpp
  Mesh/MeshETurbo.hpp
  Mesh/MeshSpherical.hpp
  Mesh/MeshSphericalExt.hpp
  Model/ANoStat.hpp
  Model/ConsItem.hpp
  Model/Constraints.hpp
  Model/CovInternal.hpp
  Model/CovParamId.hpp
  Model/ElemNostat.hpp
  Model/Model.hpp
  Model/ModelNostat.hpp
  Model/NoStatArray.hpp
  Model/NoStatFunctional.hpp
  Model/Option_AutoFit.hpp
  Model/Option_VarioFit.hpp
  Model/Tapering.hpp
  Morpho/Morpho.hpp
  Neigh/ANeigh.hpp
  Neigh/NeighBench.hpp
  Neigh/NeighCell.hpp
  Neigh/NeighImage.hpp
  Neigh/NeighMoving.hpp
  Neigh/NeighUnique.hpp
  OutputFormat/AOF.hpp
  OutputFormat/FileLAS.hpp
  OutputFormat/FileVTK.hpp
  OutputFormat/GridArcGis.hpp
  OutputFormat/GridBmp.hpp
  OutputFormat/GridEclipse.hpp
  OutputFormat/GridF2G.hpp
  OutputFormat/GridIfpEn.hpp
  OutputFormat/GridIrap.hpp
  OutputFormat/GridXYZ.hpp
  OutputFormat/GridZycor.hpp
  OutputFormat/segy.h
  OutputFormat/vtk.h
  Polygon/PolyElem.hpp
  Polygon/Polygons.hpp
  Polynomials/APolynomial.hpp
  Polynomials/Chebychev.hpp
  Polynomials/ClassicalPolynomial.hpp
  Polynomials/Hermite.hpp
  Polynomials/MonteCarlo.hpp
  Simulation/ACalcSimulation.hpp
  Simulation/BooleanObject.hpp
  Simulation/CalcSimuEden.hpp
  Simulation/CalcSimuFFT.hpp
  Simulation/CalcSimuPartition.hpp
  Simulation/CalcSimuSubstitution.hpp
  Simulation/CalcSimuTurningBands.hpp
  Simulation/SimuBoolean.hpp
  Simulation/SimuBooleanParam.hpp
  Simulation/SimuFFTParam.hpp
  Simulation/SimuPartitionParam.hpp
  Simulation/SimuRefine.hpp
  Simulation/SimuRefineParam.hpp
  Simulation/SimuSpectral.hpp
  Simulation/SimuSpherical.hpp
  Simulation/SimuSphericalParam.hpp
  Simulation/SimuSubstitutionParam.hpp
  Simulation/TurningBandDirection.hpp
  Simulation/TurningBandOperate.hpp
  Skin/ISkinFunctions.hpp
  Skin/Skin.hpp
  Space/ASpace.hpp
  Space/ASpaceObject.hpp
  Space/SpacePoint.hpp
  Space/SpaceRN.hpp
  Space/SpaceShape.hpp
  Space/SpaceSN.hpp
  Space/SpaceTarget.hpp
  Spatial/Projection.hpp
  Spatial/SpatialIndices.hpp
  Stats/Classical.hpp
  Stats/PCA.hpp
  Stats/PCAStringFormat.hpp
  Stats/Regression.hpp
  Stats/Selectivity.hpp
  Tree/Ball.hpp
  Tree/ball_algorithm.h
  Tree/KNN.hpp
  Variogram/AVario.hpp
  Variogram/DirParam.hpp
  Variogram/Vario.hpp
  Variogram/VarioParam.hpp
  Variogram/VCloud.hpp
  Variogram/VMap.hpp
)
