# Why is cmake file GLOB evil?
# https://stackoverflow.com/questions/32411963/why-is-cmake-file-glob-evil
set(SRC
  Enum/AEnum.cpp
  Enum/Enums.cpp
  Fractures/FracEnviron.cpp
  Fractures/FracFamily.cpp
  Fractures/FracFault.cpp
  Fractures/FracDesc.cpp
  Fractures/FracList.cpp
  Matrix/LinkMatrixSparse.cpp
  Matrix/AMatrix.cpp
  Matrix/AMatrixDense.cpp
  Matrix/MatrixSparse.cpp
  Matrix/MatrixInt.cpp
  Matrix/MatrixRectangular.cpp
  Matrix/AMatrixSquare.cpp
  Matrix/MatrixSquareSymmetric.cpp
  Matrix/MatrixSquareGeneral.cpp
  Matrix/MatrixFactory.cpp
  Matrix/Table.cpp
  Matrix/NF_Triplet.cpp
  API/PGSSPDE.cpp
  API/SPDE.cpp
  API/Style.cpp
  API/SPDEParam.cpp
  API/TestInheritance.cpp
  Gibbs/GibbsUPropMono.cpp
  Gibbs/GibbsFactory.cpp
  Gibbs/GibbsMultiMono.cpp
  Gibbs/GibbsMulti.cpp
  Gibbs/GibbsMMulti.cpp
  Gibbs/GibbsUMultiMono.cpp
  Gibbs/AGibbs.cpp
  Gibbs/GibbsUMulti.cpp
  LithoRule/RuleProp.cpp
  LithoRule/Rule.cpp
  LithoRule/RuleStringFormat.cpp
  LithoRule/RuleShadow.cpp
  LithoRule/RuleShift.cpp
  LithoRule/Node.cpp
  Model/ConsItem.cpp
  Model/CovParamId.cpp
  Model/NoStatArray.cpp
  Model/ANoStat.cpp
  Model/Constraints.cpp
  Model/ElemNoStat.cpp
  Model/CovInternal.cpp
  Model/Option_AutoFit.cpp
  Model/ModelNostat.cpp
  Model/Option_VarioFit.cpp
  Model/Model.cpp
  Model/NoStatFunctional.cpp
  Calculators/ACalculator.cpp
  Calculators/ACalcDbToDb.cpp
  Calculators/CalcMigrate.cpp
  Calculators/ACalcInterpolator.cpp
  Calculators/ACalcDbVarCreator.cpp
  Calculators/CalcStatistics.cpp
  Calculators/CalcGridToGrid.cpp
  Calculators/CalcSimuPost.cpp
  Calculators/CalcSimuPostDemo.cpp
  Calculators/CalcSimuPostPropByLayer.cpp
  Covariances/CovGaussian.cpp
  Covariances/CovLinear.cpp
  Covariances/CovWendland0.cpp
  Covariances/CovWendland1.cpp
  Covariances/CovWendland2.cpp
  Covariances/CovGradientFunctional.cpp
  Covariances/CovBesselK.cpp
  Covariances/CovLMGradient.cpp
  Covariances/CovPower.cpp
  Covariances/CovStorkey.cpp
  Covariances/CovGC5.cpp
  Covariances/ACovAnisoList.cpp
  Covariances/CovPenta.cpp
  Covariances/CovGamma.cpp
  Covariances/CovExponential.cpp
  Covariances/CovGC1.cpp
  Covariances/ACov.cpp
  Covariances/CovSincard.cpp
  Covariances/CovLMC.cpp
  Covariances/CovLMCTapering.cpp
  Covariances/CovLMCConvolution.cpp
  Covariances/CovLMCAnamorphosis.cpp
  Covariances/ACovGradient.cpp
  Covariances/CovGCspline2.cpp
  Covariances/CovGC3.cpp
  Covariances/CovGCspline.cpp
  Covariances/CovTriangle.cpp
  Covariances/CovCalcMode.cpp
  Covariances/CovContext.cpp
  Covariances/CovCosinus.cpp
  Covariances/CovCosExp.cpp
  Covariances/CovReg1D.cpp
  Covariances/ACovFunc.cpp
  Covariances/CovAniso.cpp
  Covariances/CovGradientNumerical.cpp
  Covariances/CovCubic.cpp
  Covariances/CovNugget.cpp
  Covariances/CovBesselJ.cpp
  Covariances/CovSpherical.cpp
  Covariances/CovCauchy.cpp
  Covariances/CovFactory.cpp
  Covariances/CovStable.cpp
  Covariances/CovMarkov.cpp
  Covariances/CovDiffusionAdvection.cpp
  Covariances/CovHelper.cpp
  Polygon/Polygons.cpp
  Polygon/PolyElem.cpp
  Core/surface.cpp
  Core/math.cpp
  Core/stats.cpp
  Core/spatial.cpp
  Core/vario.cpp
  Core/io.cpp
  Core/db.cpp
  Core/variopgs.cpp
  Core/model_auto.cpp
  Core/cluster.cpp
  Core/simtub.cpp
  Core/matrix.cpp
  Core/spill.cpp
  Core/acknowledge.cpp
  Core/geophy.cpp
  Core/potential.cpp
  Core/foxleg.cpp
  Core/util.cpp
  Core/anam.cpp
  Core/ascii.cpp
  Core/pile.cpp
  Core/mlayers.cpp
  Core/thresh.cpp
  Core/fft.cpp
  Core/convert.cpp
  Core/memory.cpp
  Core/model.cpp
  Core/krige.cpp
  Core/seismic.cpp
  Core/sparseinv.cpp
  Core/spde.cpp
  Core/dbtools.cpp
  Anamorphosis/CalcAnamTransform.cpp
  Anamorphosis/AnamContinuous.cpp
  Anamorphosis/AnamDiscrete.cpp
  Anamorphosis/AnamDiscreteDD.cpp
  Anamorphosis/AnamUser.cpp
  Anamorphosis/AAnam.cpp
  Anamorphosis/AnamHermite.cpp
  Anamorphosis/AnamDiscreteIR.cpp
  Anamorphosis/AnamEmpirical.cpp
  Anamorphosis/PPMT.cpp
  Db/Db.cpp
  Db/DbGrid.cpp
  Db/DbStringFormat.cpp
  Db/PtrGeos.cpp
  Db/DbHelper.cpp
  LinearOp/LogStats.cpp
  LinearOp/CGParam.cpp
  LinearOp/PrecisionOp.cpp
  LinearOp/TurboOptimizer.cpp
  LinearOp/ProjMatrix.cpp
  LinearOp/PrecisionOpCs.cpp
  LinearOp/ALinearOpMulti.cpp
  LinearOp/ALinearOp.cpp
  LinearOp/Identity.cpp
  LinearOp/ProdMatVect.cpp
  LinearOp/ShiftOpCs.cpp
  LinearOp/HessianOp.cpp
  LinearOp/OptimCostBinary.cpp
  LinearOp/PrecisionOpMultiConditional.cpp
  LinearOp/PrecisionOpMultiConditionalCs.cpp
  LinearOp/OptimCostColored.cpp
  LinearOp/ProjConvolution.cpp
  LinearOp/Cholesky.cpp
  Space/SpaceSN.cpp
  Space/SpaceRN.cpp
  Space/SpacePoint.cpp
  Space/SpaceTarget.cpp
  Space/ASpaceObject.cpp
  Space/ASpace.cpp
  Variogram/AVario.cpp
  Variogram/VMap.cpp
  Variogram/Vario.cpp
  Variogram/VarioParam.cpp
  Variogram/DirParam.cpp
  Basic/Limits.cpp
  Basic/AStringable.cpp
  Basic/AStringFormat.cpp
  Basic/GlobalEnvironment.cpp
  Basic/MathFunc.cpp
  Basic/Utilities.cpp
  Basic/ArgumentTest.cpp
  Basic/File.cpp
  Basic/HDF5format.cpp
  Basic/Memory.cpp
  Basic/VectorHelper.cpp
  Basic/FunctionalSpirale.cpp
  Basic/Law.cpp
  Basic/Interval.cpp
  Basic/Indirection.cpp
  Basic/Tensor.cpp
  Basic/Timer.cpp
  Basic/Rotation.cpp
  Basic/AException.cpp
  Basic/ASerializable.cpp
  Basic/String.cpp
  Basic/Grid.cpp
  Basic/AFunctional.cpp
  Basic/CSVformat.cpp
  Basic/NamingConvention.cpp
  Basic/Utilities.cpp
  Basic/OptDbg.cpp
  Basic/OptCst.cpp
  Basic/OptCustom.cpp
  Basic/Plane.cpp
  Basic/FFT.cpp
  Basic/PolyLine2D.cpp
  Basic/VectorNumT.cpp
  Basic/VectorT.cpp
  Geometry/GeometryHelper.cpp
  Geometry/ABiTargetCheck.cpp
  Geometry/BiTargetCheckDistance.cpp
  Geometry/BiTargetCheckFaults.cpp
  Geometry/BiTargetCheckCell.cpp
  Geometry/BiTargetCheckBench.cpp
  Geometry/BiTargetCheckCode.cpp
  Geometry/BiTargetCheckDate.cpp
  Geometry/BiTargetCheckGeometry.cpp
  Arrays/AArray.cpp
  Arrays/Array.cpp
  Arrays/BImage.cpp
  Arrays/BImageStringFormat.cpp
  Faults/Faults.cpp
  Boolean/ShapeParameter.cpp
  Boolean/AShape.cpp
  Boolean/ShapeParallelepiped.cpp
  Boolean/ShapeEllipsoid.cpp
  Boolean/ShapeParaboloid.cpp
  Boolean/ShapeHalfEllipsoid.cpp
  Boolean/ShapeHalfParaboloid.cpp
  Boolean/ShapeHalfSinusoid.cpp
  Boolean/ModelBoolean.cpp
  Polynomials/Chebychev.cpp
  Polynomials/APolynomial.cpp
  Polynomials/Hermite.cpp
  Polynomials/ClassicalPolynomial.cpp
  Polynomials/MonteCarlo.cpp
  Mesh/AMesh.cpp
  Mesh/LinkSphTriangle.cpp
  Mesh/MeshETurbo.cpp
  Mesh/Delaunay.cpp
  Mesh/MeshSpherical.cpp
  Mesh/MeshSphericalExt.cpp
  Mesh/MeshEStandard.cpp
  Morpho/Morpho.cpp
  Stats/Classical.cpp
  Stats/PCA.cpp
  Stats/PCAStringFormat.cpp
  Stats/Selectivity.cpp
  Stats/Regression.cpp
  Drifts/DriftM.cpp
  Drifts/DriftF.cpp
  Drifts/DriftFactory.cpp
  Drifts/ADrift.cpp
  Drifts/DriftList.cpp
  Neigh/ANeigh.cpp
  Neigh/NeighUnique.cpp
  Neigh/NeighImage.cpp
  Neigh/NeighMoving.cpp
  Neigh/NeighBench.cpp
  Neigh/NeighCell.cpp
  Estimation/KrigingSystem.cpp
  Estimation/CalcKriging.cpp
  Estimation/CalcKrigingFactors.cpp
  Estimation/CalcSimpleInterpolation.cpp
  Estimation/CalcImage.cpp
  Estimation/CalcGlobal.cpp
  OutputFormat/AOF.cpp
  OutputFormat/GridIfpEn.cpp
  OutputFormat/GridEclipse.cpp
  OutputFormat/GridXYZ.cpp
  OutputFormat/GridZycor.cpp
  OutputFormat/GridIrap.cpp
  OutputFormat/GridBmp.cpp
  OutputFormat/GridArcGis.cpp
  OutputFormat/FileVTK.cpp
  OutputFormat/FileLAS.cpp
  OutputFormat/GridF2G.cpp
  OutputFormat/vtk.cpp
  OutputFormat/segy.cpp
  Simulation/ACalcSimulation.cpp
  Simulation/CalcSimuTurningBands.cpp
  Simulation/TurningDirection.cpp
  Simulation/BooleanObject.cpp
  Simulation/SimuBoolean.cpp
  Simulation/SimuBooleanParam.cpp
  Simulation/SimuSpherical.cpp
  Simulation/SimuSphericalParam.cpp
  Simulation/CalcSimuSubstitution.cpp
  Simulation/SimuSubstitutionParam.cpp
  Simulation/CalcSimuPartition.cpp
  Simulation/SimuPartitionParam.cpp
  Simulation/SimuFFTParam.cpp
  Simulation/CalcSimuFFT.cpp
  Simulation/SimuRefineParam.cpp
  Simulation/SimuRefine.cpp
  Simulation/CalcSimuEden.cpp
  Basic/AFunction.cpp
  Skin/Skin.cpp
  Tree/Ball.cpp
  Tree/KNN.cpp
  Tree/ball_algorithm.cpp
  Tree/metrics.cpp
  Tree/neighbors_heap.cpp
)
