# Why is cmake file GLOB evil?
# https://stackoverflow.com/questions/32411963/why-is-cmake-file-glob-evil
set(SRC
  API/newAPIs.cpp
  Enum/AEnum.cpp
  Enum/Enums.cpp
  Fractures/FracEnviron.cpp
  Fractures/FracFamily.cpp
  Fractures/FracFault.cpp
  Fractures/FracDesc.cpp
  Fractures/FracList.cpp
  Matrix/AMatrix.cpp
  Matrix/MatrixSparse.cpp
  Matrix/MatrixInt.cpp
  Matrix/MatrixDense.cpp
  Matrix/MatrixSquare.cpp
  Matrix/MatrixSymmetric.cpp
  Matrix/MatrixFactory.cpp
  Matrix/EigenVectors.cpp
  Matrix/Table.cpp
  Matrix/NF_Triplet.cpp
  API/SPDE.cpp
  API/Style.cpp
  API/SPDEParam.cpp
  API/TestInheritance.cpp
  API/Potential.cpp
  Gibbs/GibbsUPropMono.cpp
  Gibbs/GibbsFactory.cpp
  Gibbs/GibbsMultiMono.cpp
  Gibbs/GibbsMulti.cpp
  Gibbs/GibbsMMulti.cpp
  Gibbs/GibbsUMultiMono.cpp
  Gibbs/AGibbs.cpp
  Gibbs/GibbsUMulti.cpp
  LithoRule/PropDef.cpp
  LithoRule/RuleProp.cpp
  LithoRule/Rule.cpp
  LithoRule/RuleStringFormat.cpp
  LithoRule/RuleShadow.cpp
  LithoRule/RuleShift.cpp
  LithoRule/Node.cpp
  Model/ModelGeneric.cpp
  Model/GaussianProcess.cpp
  Model/ModelCovList.cpp
  Model/ConsItem.cpp
  Model/CovParamId.cpp
  Model/Constraints.cpp
  Model/ElemNoStat.cpp
  Model/CovInternal.cpp
  Model/Option_AutoFit.cpp
  Model/Option_VarioFit.cpp
  Model/Model.cpp
  Model/ModelOptimParam.cpp
  Model/ModelOptimVario.cpp
  Model/ModelOptimVMap.cpp
  Model/AModelFitSills.cpp
  Model/ModelFitSillsVario.cpp
  Model/ModelFitSillsVMap.cpp
  Calculators/ACalculator.cpp
  Calculators/ACalcDbToDb.cpp
  Calculators/CalcMigrate.cpp
  Calculators/ACalcInterpolator.cpp
  Calculators/ACalcDbVarCreator.cpp
  Calculators/CalcStatistics.cpp
  Calculators/CalcGridToGrid.cpp
  Calculators/CalcSimuPost.cpp
  Calculators/CalcSimuPostDemo.cpp
  Calculators/CalcSimuPostPropByLayer.cpp
  Covariances/AKernel.cpp
  Covariances/KernelGaussian.cpp
  Covariances/KernelLinear.cpp
  Covariances/KernelWendland0.cpp
  Covariances/KernelWendland1.cpp
  Covariances/KernelWendland2.cpp
  Covariances/KernelMatern.cpp
  Covariances/KernelPower.cpp
  Covariances/KernelStorkey.cpp
  Covariances/KernelGC5.cpp
  Covariances/KernelPenta.cpp
  Covariances/KernelGamma.cpp
  Covariances/KernelExponential.cpp
  Covariances/KernelGC1.cpp
  Covariances/KernelSincard.cpp
  Covariances/KernelGCspline2.cpp
  Covariances/KernelGC3.cpp
  Covariances/KernelGCspline.cpp
  Covariances/KernelTriangle.cpp
  Covariances/KernelCosinus.cpp
  Covariances/KernelCosExp.cpp
  Covariances/KernelReg1D.cpp
  Covariances/KernelCubic.cpp
  Covariances/KernelNugget.cpp
  Covariances/KernelBesselJ.cpp
  Covariances/KernelSpherical.cpp
  Covariances/KernelCauchy.cpp
  Covariances/KernelCauchyGen.cpp
  Covariances/KernelStable.cpp
  Covariances/KernelMarkov.cpp
  Covariances/KernelGeometric.cpp
  Covariances/KernelPoisson.cpp
  Covariances/KernelLinearSph.cpp
  Covariances/TabNoStatCovAniso.cpp
  Covariances/TabNoStatSills.cpp
  Covariances/TabNoStat.cpp
  Covariances/ParamId.cpp
  Covariances/CovBase.cpp
  Covariances/CovProportional.cpp
  Covariances/ANoStat.cpp
  Covariances/NoStatArray.cpp
  Covariances/NoStatOnMesh.cpp
  Covariances/NoStatFunctional.cpp
  Covariances/CovGradientGeneric.cpp
  Covariances/CovGradientAnalytic.cpp
  Covariances/CovList.cpp
  Covariances/CovAnisoList.cpp
  Covariances/ACov.cpp
  Covariances/CovLMCTapering.cpp
  Covariances/CovLMCConvolution.cpp
  Covariances/CovLMCAnamorphosis.cpp
  Covariances/CovCalcMode.cpp
  Covariances/CovContext.cpp
  Covariances/CorAniso.cpp
  Covariances/CorFactorized.cpp
  Covariances/CorGaussianMixture.cpp
  Covariances/CorGneiting.cpp
  Covariances/CorMatern.cpp
  Covariances/CovAniso.cpp
  Covariances/CovFactory.cpp
  Covariances/CovDiffusionAdvection.cpp
  Covariances/CovHelper.cpp
  Polygon/Polygons.cpp
  Polygon/PolyElem.cpp
  Core/stats.cpp
  Core/io.cpp
  Core/db.cpp
  Core/model_auto.cpp
  Core/cluster.cpp
  Core/simtub.cpp
  Core/spill.cpp
  Core/acknowledge.cpp
  Core/geophy.cpp
  Core/foxleg.cpp
  Core/util.cpp
  Core/ascii.cpp
  Core/thresh.cpp
  Core/fft.cpp
  Core/convert.cpp
  Core/model.cpp
  Core/krige.cpp
  Core/seismic.cpp
  Core/sparseinv.cpp
  Core/spde.cpp
  Core/dbtools.cpp
  Anamorphosis/CalcAnamTransform.cpp
  Anamorphosis/AnamContinuous.cpp
  Anamorphosis/AnamDiscrete.cpp
  Anamorphosis/AnamDiscreteDD.cpp
  Anamorphosis/AnamUser.cpp
  Anamorphosis/AAnam.cpp
  Anamorphosis/AnamHermite.cpp
  Anamorphosis/AnamDiscreteIR.cpp
  Anamorphosis/AnamEmpirical.cpp
  Anamorphosis/PPMT.cpp
  Db/Db.cpp
  Db/DbGrid.cpp
  Db/DbLine.cpp
  Db/DbGraphO.cpp
  Db/DbMeshTurbo.cpp
  Db/DbMeshStandard.cpp
  Db/DbStringFormat.cpp
  Db/PtrGeos.cpp
  Db/DbHelper.cpp
  Db/RankHandler.cpp
  LinearOp/LogStats.cpp
  LinearOp/CGParam.cpp
  LinearOp/InvNuggetOp.cpp
  LinearOp/PrecisionOp.cpp
  LinearOp/TurboOptimizer.cpp
  LinearOp/ProjMatrix.cpp
  LinearOp/ProjMulti.cpp
  LinearOp/ProjMultiMatrix.cpp
  LinearOp/ProjComposition.cpp
  LinearOp/ProjZero.cpp
  LinearOp/PrecisionOpMatrix.cpp
  LinearOp/ALinearOpMulti.cpp
  LinearOp/ALinearOp.cpp
  LinearOp/ScaleOp.cpp
  LinearOp/AShiftOp.cpp
  LinearOp/ShiftOpMatrix.cpp
  LinearOp/ShiftOpStencil.cpp
  LinearOp/HessianOp.cpp
  LinearOp/OptimCostBinary.cpp
  LinearOp/IProj.cpp
  LinearOp/PrecisionOpMulti.cpp
  LinearOp/PrecisionOpMultiMatrix.cpp
  LinearOp/OptimCostColored.cpp
  LinearOp/ProjConvolution.cpp
  LinearOp/ACholesky.cpp
  LinearOp/CholeskySparse.cpp
  LinearOp/CholeskyDense.cpp
  LinearOp/SPDEOp.cpp
  LinearOp/SPDEOpMatrix.cpp
  LinearOp/ASimulable.cpp
  LinearOp/ASimulableMatrix.cpp
  LinearOp/MatrixSymmetricSim.cpp
  LinearOp/LinearOpHelper.cpp
  LinearOp/MultiGridSolver.cpp
  LinearOp/MultiGridSPDE.cpp
  MLayers/MLayers.cpp
  Space/SpaceSN.cpp
  Space/SpaceRN.cpp
  Space/SpacePoint.cpp
  Space/SpaceTarget.cpp
  Space/ASpaceObject.cpp
  Space/ASpace.cpp
  Space/SpaceComposite.cpp
  Spatial/Projection.cpp
  Spatial/SpatialIndices.cpp
  Variogram/AVario.cpp
  Variogram/VMap.cpp
  Variogram/VCloud.cpp
  Variogram/Vario.cpp
  Variogram/VarioParam.cpp
  Variogram/DirParam.cpp
  Variogram/VarioOrder.cpp
  Variogram/Variograms.cpp
  Basic/Optim.cpp
  Basic/ParamInfo.cpp
  Basic/ListParams.cpp
  Basic/Limits.cpp
  Basic/StringHelper.cpp
  Basic/AStringable.cpp
  Basic/AStringFormat.cpp
  Basic/GlobalEnvironment.cpp
  Basic/MathFunc.cpp
  Basic/Utilities.cpp
  Basic/ArgumentTest.cpp
  Basic/File.cpp
  Basic/Memory.cpp
  Basic/VectorHelper.cpp
  Basic/FunctionalSpirale.cpp
  Basic/Law.cpp
  Basic/LawStable.cpp
  Basic/Interval.cpp
  Basic/Indirection.cpp
  Basic/Tensor.cpp
  Basic/Timer.cpp
  Basic/Rotation.cpp
  Basic/AException.cpp
  Basic/ASerializable.cpp
  Basic/String.cpp
  Basic/Grid.cpp
  Basic/AFunctional.cpp
  Basic/CSVformat.cpp
  Basic/NamingConvention.cpp
  Basic/Utilities.cpp
  Basic/OptDbg.cpp
  Basic/OptCst.cpp
  Basic/OptCustom.cpp
  Basic/Plane.cpp
  Basic/FFT.cpp
  Basic/SerializeNeutralFile.cpp
  Basic/PolyLine2D.cpp
  Basic/Convolution.cpp
  Basic/Message.cpp
  Geometry/GeometryHelper.cpp
  Geometry/ABiTargetCheck.cpp
  Geometry/BiTargetCheckDistance.cpp
  Geometry/BiTargetCheckFaults.cpp
  Geometry/BiTargetCheckCell.cpp
  Geometry/BiTargetCheckBench.cpp
  Geometry/BiTargetCheckCode.cpp
  Geometry/BiTargetCheckDate.cpp
  Geometry/BiTargetCheckGeometry.cpp
  Arrays/AArray.cpp
  Arrays/Array.cpp
  Arrays/BImage.cpp
  Arrays/BImageStringFormat.cpp
  Faults/Faults.cpp
  Boolean/ShapeParameter.cpp
  Boolean/AShape.cpp
  Boolean/ShapeParallelepiped.cpp
  Boolean/ShapeEllipsoid.cpp
  Boolean/ShapeParaboloid.cpp
  Boolean/ShapeHalfEllipsoid.cpp
  Boolean/ShapeHalfParaboloid.cpp
  Boolean/ShapeHalfSinusoid.cpp
  Boolean/ModelBoolean.cpp
  Polynomials/Chebychev.cpp
  Polynomials/APolynomial.cpp
  Polynomials/Hermite.cpp
  Polynomials/ClassicalPolynomial.cpp
  Polynomials/MonteCarlo.cpp
  Mesh/AMesh.cpp
  Mesh/LinkSphTriangle.cpp
  Mesh/MeshETurbo.cpp
  Mesh/Delaunay.cpp
  Mesh/MeshSpherical.cpp
  Mesh/MeshSphericalExt.cpp
  Mesh/MeshEFaulted.cpp
  Mesh/MeshEStandard.cpp
  Mesh/VectorMeshes.cpp
  Morpho/Morpho.cpp
  Stats/Classical.cpp
  Stats/PCA.cpp
  Stats/PCAStringFormat.cpp
  Stats/Selectivity.cpp
  Stats/Regression.cpp
  Drifts/DriftM.cpp
  Drifts/DriftF.cpp
  Drifts/DriftFactory.cpp
  Drifts/ADrift.cpp
  Drifts/DriftList.cpp
  Neigh/ANeigh.cpp
  Neigh/NeighUnique.cpp
  Neigh/NeighImage.cpp
  Neigh/NeighMoving.cpp
  Neigh/NeighBench.cpp
  Neigh/NeighCell.cpp
  Estimation/Estimations.cpp
  Estimation/AModelOptim.cpp
  Estimation/ALikelihood.cpp
  Estimation/AModelOptimFactory.cpp
  Estimation/KrigingSystem.cpp
  Estimation/KrigingSystemSimpleCase.cpp
  Estimation/KrigingAlgebra.cpp
  Estimation/KrigingAlgebraSimpleCase.cpp
  Estimation/CalcKriging.cpp
  Estimation/CalcKrigingSimpleCase.cpp
  Estimation/CalcKrigingFactors.cpp
  Estimation/CalcKrigingGradient.cpp
  Estimation/CalcSimpleInterpolation.cpp
  Estimation/CalcImage.cpp
  Estimation/CalcGlobal.cpp
  Estimation/KrigOpt.cpp
  Estimation/Vecchia.cpp
  Estimation/Likelihood.cpp
  OutputFormat/AOF.cpp
  OutputFormat/GridIfpEn.cpp
  OutputFormat/GridEclipse.cpp
  OutputFormat/GridXYZ.cpp
  OutputFormat/GridZycor.cpp
  OutputFormat/GridIrap.cpp
  OutputFormat/GridBmp.cpp
  OutputFormat/GridArcGis.cpp
  OutputFormat/FileVTK.cpp
  OutputFormat/FileLAS.cpp
  OutputFormat/GridF2G.cpp
  OutputFormat/vtk.cpp
  OutputFormat/segy.cpp
  Simulation/Simulations.cpp
  Simulation/ACalcSimulation.cpp
  Simulation/ACalcSimuGaussian.cpp
  Simulation/CalcSimuTurningBands.cpp
  Simulation/CalcSimuSpectral.cpp
  Simulation/CalcSimuPGS.cpp
  Simulation/CalcSimuBoolean.cpp
  Simulation/TurningBandDirection.cpp
  Simulation/TurningBandOperate.cpp
  Simulation/SimuSpectralRN.cpp
  Simulation/SpectrumOnRN.cpp
  Simulation/SimuSpectralS2.cpp
  Simulation/BooleanObject.cpp
  Simulation/SimuBooleanParam.cpp
  Simulation/SimuSpherical.cpp
  Simulation/SimuSphericalParam.cpp
  Simulation/CalcSimuSubstitution.cpp
  Simulation/SimuSubstitutionParam.cpp
  Simulation/CalcSimuPartition.cpp
  Simulation/SimuPartitionParam.cpp
  Simulation/SimuFFTParam.cpp
  Simulation/CalcSimuFFT.cpp
  Simulation/SimuRefineParam.cpp
  Simulation/CalcSimuRefine.cpp
  Simulation/CalcSimuEden.cpp
  Basic/AFunction.cpp
  Skin/Skin.cpp
  Transform/ATransform.cpp
  Transform/TuckeyGH.cpp
  Transform/YeoJohnson.cpp
  Tree/Ball.cpp
  Tree/BallFaulted.cpp
  Tree/KNN.cpp
  Tree/ball_algorithm.cpp
  Tree/neighbors_heap.cpp
  PluriGaussian/TracePGS.cpp
  PluriGaussian/CorPGS.cpp
  PluriGaussian/DiscretePGS.cpp
  PluriGaussian/CalcModelPGS.cpp
  PluriGaussian/PileRelem.cpp
  PluriGaussian/PileSplit.cpp
)
