name: check_code

on:
  # Permit calling trigger
  workflow_call:
  # Permit manual trigger
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Manual'
        required: false
        default: ''

env:
  CMAKE_EXPORT_COMPILE_COMMANDS: ON


jobs:

  # ----------------------- #
  # Check source formatting #
  # ----------------------- #
  check-formatting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Setup uv
      uses: astral-sh/setup-uv@v6
      with:
        activate-environment: true

    - name: Install formatters
      run: |
        uv pip install clang-format cmake-format ruff

    - name: Pass ruff format on Python sources
      run: |
        ruff format --check

    - name: Pass ruff check on Python sources [NOT ENFORCED]
      continue-on-error: true
      run: |
        ruff check

    - name: Use clang-format to detect formatting issues
      if: false                   # disabled for now, waiting for clang-format
      run: |
        git ls-files | grep -E "\.cpp$|\.cxx$|\.h$|\.hpp$" | xargs clang-format -n -Werror

    - name: Check line endings (Unix rather than DOS)
      if: false
      run: |
        ! git ls-files | xargs file "{}" ";" | grep CRLF

    - name: Check files not ending with a newline [NOT ENFORCED]
      run: |
        for f in $(git ls-files | grep -Ev 'png$|ico$' ); do
          test $(tail -c 1 $f | wc -l) -eq 0 && echo $f || true
        done

    - name: Check for files containing Unicode characters [NOT ENFORCED]
      run: |
        git ls-files | xargs file | grep Unicode || true

    - name: Check for empty files
      if: false
      run: |
        ! git ls-files | xargs file | grep empty

    - name: No "using namespace" directive in header files
      if: false
      run: |
        ! git ls-files \
          | grep -E "\.h$|\.hpp$" \
          | xargs grep "using namespace"


  # ----------------------- #
  # Check compiler warnings #
  # ----------------------- #
  check-warnings:
    runs-on: macos-latest
    strategy:
      matrix:
        opt: [Debug, Release]
        hdf5: [USE_HDF5=ON, USE_HDF5=OFF]
        span: [USE_BOOST_SPAN=ON, USE_BOOST_SPAN=OFF]

    steps:
    - uses: actions/checkout@v4

    - name: Install macOS dependencies
      run: |
        brew install llvm
        brew install boost
        brew install eigen
        brew install nlopt
        brew install hdf5
        echo "$(brew --prefix llvm)/bin" >> $GITHUB_PATH

    - name: Create & configure gstlearn build directory
      run: |
        mkdir build
        cd build
        cmake \
          -DCMAKE_BUILD_TYPE=${{ matrix.opt }} \
          -D${{ matrix.hdf5 }} \
          -D${{ matrix.span }} \
          -DBUILD_TESTING=ON \
          $GITHUB_WORKSPACE
      env:
        CC: clang
        CXX: clang++

    - name: Use clang-check for compiler warnings
      run: |
        git ls-files \
        | grep -E "src|include" \
        | grep -E "\.cpp$|\.hpp$" \
        | xargs -n1 -P$(sysctl -n hw.physicalcpu) -t \
            xcrun clang-check -p build --extra-arg=-Werror


  # ------------- #
  # Code lint job #
  # ------------- #
  lint-code:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        config:
          # - {tidy: true, sa: false, dox: false}
          # - {tidy: false, sa: true, dox: false}
          - {tidy: false, sa: false, dox: true}

    steps:
    - uses: actions/checkout@v4

    - name: Install Ubuntu dependencies
      run: |
        sudo apt update
        # gstlearn dependencies
        sudo apt install -y \
          libhdf5-dev \
          libopenmpi-dev \
          libboost-system-dev \
          libeigen3-dev \
          libnlopt-dev \
          libomp-dev \
          clang-tools \
          clang-tidy \
          doxygen \

    - name: Create & configure gstlearn build directory
      run: |
        mkdir build
        cd build
        cmake \
          -DCMAKE_BUILD_TYPE=Debug \
          -DBUILD_TESTING=ON \
          -DBUILD_DOC=ON \
          $GITHUB_WORKSPACE

    - name: Use clang-tidy to lint code
      if: matrix.config.tidy
      run: |
        git ls-files \
        | grep src \
        | grep -E "\.cpp$|\.cxx$" \
        | xargs -n1 -P$(nproc) -t \
            clang-tidy -p build --warnings-as-errors="*" 2> /dev/null

    - name: Use Clang static analyzer
      if: matrix.config.sa
      run: |
        git ls-files \
        | grep src \
        | grep -E "\.cpp$|\.cxx$" \
        | xargs -n1 -P$(nproc) -t \
            xcrun clang-check -p build --analyze --extra-arg=-Werror 2> /dev/null

    - name: Check Doxygen documentation warnings
      if: matrix.config.dox
      run: |
        cd build
        ! cmake --build . --target doxygen |& grep warning
