name: coverage-tests_r

on:
  # Permit calling trigger
  workflow_call:
  # Permit manual trigger
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Manual'
        required: false
        default: ''

jobs:
  build:
    runs-on: ${{matrix.os}}
    strategy:
      fail-fast: false
      matrix:
        # Last releases from here https://cran.r-project.org/src/base/R-4/
        r_version: [4.2.3, 4.3.3, 4.4.3, 4.5.0]
        # See the list here: https://github.com/actions/runner-images#available-images
        os: [ubuntu-22.04, ubuntu-24.04, windows-2019, windows-2022, macos-13, macos-14, macos-15]
        exclude:
          - os: ubuntu-22.04
            r_version: 4.2.3  # ggpubr install fails
          - os: ubuntu-24.04
            r_version: 4.2.3  # ggpubr install fails
          - os: macos-13
            r_version: 4.3.3
          - os: macos-13
            r_version: 4.4.3
          - os: macos-13
            r_version: 4.5.0

    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        if [[ "${{ matrix.os }}" =~ ^"macos" ]]; then
          brew install llvm
        fi
      shell: bash

    - name: Setup R Version
      uses: r-lib/actions/setup-r@v2
      with:
        r-version: ${{matrix.r_version}}

    # https://stackoverflow.com/questions/69639782/installing-gfortran-on-macbook-with-apple-m1-chip-for-use-in-r
    - name: Fix gfortran path for R
      run: |
        if [[ "${{ matrix.os }}" =~ ^"macos" ]]; then
          mkdir -p ~/.R
          echo "FC      = /usr/local/bin/gfortran" >> ~/.R/Makevars
          echo "F77     = /usr/local/bin/gfortran" >> ~/.R/Makevars
          echo "FLIBS   = -L/usr/local/bin/gfortran/lib" >> ~/.R/Makevars
        fi
      shell: bash

    - name: Install R dependencies
      uses: r-lib/actions/setup-r-dependencies@v2
      with:
        packages: ggpubr, ggplot2, ggnewscale
        install-pandoc: false
        
    - name: Install gstlearn
      run: Rscript -e "install.packages(c('gstlearn'), repos='https://soft.mines-paristech.fr/cran/', dependencies = TRUE)"

    - name: Run the r tests
      run: |
        Rscript tests/r/test_Arguments.R
        Rscript tests/r/test_Assessors.R
        Rscript tests/r/test_Matrix.R

