name: coverage-tests_r

on:
  # Permit calling trigger
  workflow_call:
  # Permit manual trigger
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Manual'
        required: false
        default: ''

jobs:
  build:
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        # Last releases from here https://cran.r-project.org/src/base/R-4/
        r_version: [4.0.5, 4.1.3, 4.2.3, 4.3.2]
        # See the list here: https://github.com/actions/runner-images#available-images
        os: [ubuntu-20.04, ubuntu-22.04, windows-2019, windows-2022, macos-12, macos-13, macos-14]
        exclude:
          - os: macos-12
            r_version: 4.3.2
          - os: macos-13
            r_version: 4.3.2
          - os: macos-14
            r_version: 4.0.5
          
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup R Version
      uses: r-lib/actions/setup-r@v2
      with:
        r-version: ${{matrix.r_version}}

    - name: Install swigex
      run: Rscript -e "install.packages(c('gstlearn'), repos='https://soft.mines-paristech.fr/cran/', dependencies = TRUE)"

    - name: Run the r test
      run: |
        Rscript tests/r/test_Arguments.R
        Rscript tests/r/test_Assessors.R
        Rscript tests/r/test_Matrix.R
      