name: nonreg-tests_windows-2019-rtools

on:
  # Deactivate the workflow
  #push:
  #  branches-ignore:
  #    - '**'
  # Activate the workflow at each push on dev branch
  push:
    branches: [ dev ]
  # Activate the workflow at each pull request on dev branch
  pull_request:
    branches: [ dev ]
  # Permit manual trigger
  # Activate the workflow every day at 23:30 UTC = for Paris 00:30 (summer) or 01:30 (winter)
  #schedule:
  #  # * is a special character in YAML so you have to quote the string
  #  - cron:  '30 23 * * *'
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Manual'
        required: false
        default: ''

env:
  # Customize the CMake build type here (Release, Debug)
  BUILD_TYPE: Release
  BUILD_DIR : build
  R_VERSION  : 4.1.3
  GENERATOR : "MSYS Makefiles"
  SWIG_ROOT  : ${{github.workspace}}\swig_420b
  BOOST_ROOT : ${{github.workspace}}\boost
  BOOST_VERSION: "1.72.0"
  EIGEN_ROOT : ${{github.workspace}}\eigen
  EIGEN_VERSION : "3.4.0"
  
jobs:
  
  build:
    runs-on: windows-2019

    steps:
    - uses: actions/checkout@v3

    - name: Setup R Version
      uses: r-lib/actions/setup-r@v2
      with:
        r-version: ${{env.R_VERSION}}

    - name: Install R dependencies
      run: Rscript -e "install.packages(c('devtools'), repos='https://cloud.r-project.org/', dependencies = TRUE)"

    - name: Install the customized SWIG from source under windows
      uses: fabien-ors/install-swig-windows-action@v2
      with:
        swig-root: ${{env.SWIG_ROOT}}

    - name: Install the Boost headers
      uses: ./.github/workflows/install-boost-windows
      with:
        boost-root: ${{env.BOOST_ROOT}}
        boost-version: ${{env.BOOST_VERSION}}

    - name: Install the Eigen headers
      uses: ./.github/workflows/install-eigen-windows
      with:
        eigen-root: ${{env.EIGEN_ROOT}}
        eigen-version: ${{env.EIGEN_VERSION}}

    - name: Configure CMake
      run: cmake -B${{env.BUILD_DIR}} -G "${{env.GENERATOR}}" -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DBUILD_R=ON -DBUILD_PYTHON=OFF -DUSE_HDF5=OFF -DSWIG_EXECUTABLE=${{env.SWIG_ROOT}}/bin/swig -DBoost_ROOT="${{env.BOOST_ROOT}}" -DEigen3_ROOT="${{env.EIGEN_ROOT}}"

    - name: Compile, install package and execute non-regression tests
      run: cmake --build ${{env.BUILD_DIR}} --target check
