name: nonreg-tests

on:
  # Activate the workflow at each push on dev branch
  push:
    branches: [ dev ]
  # Activate the workflow at each pull request on dev branch
  pull_request:
    branches: [ dev ]
  # Activate the workflow every day at 23:30 UTC = for Paris 00:30 (summer) or 01:30 (winter)
  schedule:
    # * is a special character in YAML so you have to quote the string
    - cron:  '30 23 * * *'
  # Permit manual trigger
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Manual'
        required: false
        default: ''

jobs:
  call-macos-latest:
    uses: ./.github/workflows/nonreg-tests_macos-latest.yml
  call-windows-latest-msvc:
    uses: ./.github/workflows/nonreg-tests_windows-latest-msvc.yml
  call-windows-latest-rtools:
    uses: ./.github/workflows/nonreg-tests_windows-latest-rtools.yml
  call-ubuntu-latest:
    uses: ./.github/workflows/nonreg-tests_ubuntu-latest.yml
