name: nonreg-demos-courses_ubuntu-latest

on:
  # Activate the workflow at each push on dev branch
  push:
    branches: [ dev ]
  # Activate the workflow at each pull request on dev branch
  pull_request:
    branches: [ dev ]
  # Activate the workflow every day at 23:30 UTC = for Paris 00:30 (summer) or 01:30 (winter)
  schedule:
    # * is a special character in YAML so you have to quote the string
    - cron:  '30 23 * * *'
  # Permit manual trigger
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Manual'
        required: false
        default: ''

jobs:
  call-python:
    uses: ./.github/workflows/nonreg-demos-courses_python_ubuntu-latest.yml
  call-r:
    uses: ./.github/workflows/nonreg-demos-courses_r_ubuntu-latest.yml
