name: nonreg-tests_windows-latest-rtools

on:
  # Permit calling trigger
  workflow_call:
  # Activate the workflow at each push on dev branch
  #push:
  #  branches: [ dev ]
  # Activate the workflow at each pull request on dev branch
  #pull_request:
  #  branches: [ dev ]
  # Permit manual trigger
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Manual'
        required: false
        default: ''

env:
  # Customize the CMake build type here (Release, Debug)
  CMAKE_BUILD_TYPE : Release
  BUILD_DIR : build
  CMAKE_GENERATOR : "MSYS Makefiles"
  R_VERSION : "4.3.2"
  SWIG_ROOT : ${{github.workspace}}\swig_420b
  CMAKE_TOOLCHAIN_FILE : C:\vcpkg\scripts\buildsystems\vcpkg.cmake

jobs:

  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup R Version
      uses: r-lib/actions/setup-r@v2
      with:
        r-version: ${{env.R_VERSION}}

    - name: Install roxygen2
      uses: r-lib/actions/setup-r-dependencies@v2
      with:
        packages: roxygen2
        install-pandoc: false

    - name: Install dependencies
      run: |
        echo '{
          "dependencies": [ "boost-math", "eigen3" ],
          "builtin-baseline": "bcf3d00d2116056fda0ce47615f6074ffecb7524"
        }' > vcpkg.json
        vcpkg install

    - name: Install the customized SWIG from source
      uses: fabien-ors/install-swig-windows-action@v2
      with:
        swig-root: ${{env.SWIG_ROOT}}
        generator: "Visual Studio 17 2022"

    - name: Configure build directory
      run: |
        cmake `
          -B${{ env.BUILD_DIR }} `
          -DBUILD_R=ON `
          -DBUILD_PYTHON=OFF `
          -DSWIG_EXECUTABLE=${{env.SWIG_ROOT}}/bin/swig

    - name: Build the package
      run: |
        cmake --build ${{env.BUILD_DIR}} --parallel 3

    - name: Install packages and execute non-regression tests
      run: |
        cmake --build ${{env.BUILD_DIR}} --parallel 3 --target check

    - name: Compress output logs and neutral files
      if: success() || failure()
      shell: powershell
      run: |
        cd ${{env.BUILD_DIR}}/tests
        Get-ChildItem -Recurse -Filter '*.out' | Select-Object -ExpandProperty Fullname | Resolve-Path -Relative > logs.txt
        foreach ($filename in Get-Content .\logs.txt)
        {
            Compress-Archive -Update $filename .\rtools-logs.zip
        }
        cd $HOME/gstlearn_dir
        Get-ChildItem -Recurse -Filter '*.*' | Select-Object -ExpandProperty Fullname | Resolve-Path -Relative > neutral.txt
        foreach ($filename in Get-Content .\neutral.txt)
        {
            Compress-Archive -Update $filename .\rtools-neutral.zip
        }
        Move-Item -Path rtools-neutral.zip -Destination ${{github.workspace}}

    - name: Publish output logs as artefact
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: rtools-nonreg-logs
        path: ${{env.BUILD_DIR}}/tests/rtools-logs.zip

    - name: Publish output neutral files as artefact
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: rtools-neutral-files
        path: ${{github.workspace}}/rtools-neutral.zip
