name: nonreg-tests

on:
  # Activate the workflow at each push on main branch
  push:
    branches: [ dev ]
  # Activate the workflow at each pull request on main branch
  pull_request:
    branches: [ dev ]
  # Permit manual trigger
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Manual'
        required: false
        default: ''

# TODO: restore all non reg tests
jobs:
  call-macos-latest:
    uses: ./.github/workflows/nonreg-tests_macos-latest.yml
  call-windows-latest-msvc:
    uses: ./.github/workflows/nonreg-tests_windows-latest-msvc.yml
#  call-windows-latest-rtools:
#    uses: ./.github/workflows/nonreg-tests_windows-latest-rtools.yml
#  call-ubuntu-latest:
#    uses: ./.github/workflows/nonreg-tests_ubuntu-latest.yml
