name: nonreg-tests_windows-latest-rtools

on:
  # Permit calling trigger
  workflow_call:
  # Activate the workflow at each push on dev branch
  #push:
  #  branches: [ dev ]
  # Activate the workflow at each pull request on dev branch
  #pull_request:
  #  branches: [ dev ]
  # Permit manual trigger
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Manual'
        required: false
        default: ''

env:
  # Customize the CMake build type here (Release, Debug)
  CMAKE_BUILD_TYPE : Release
  BUILD_DIR : build
  CMAKE_GENERATOR : "MSYS Makefiles"
  R_VERSION : "4.6.0"
  SWIG_ROOT : ${{github.workspace}}\swig
  GSTLEARN_OUTPUT_DIR: ${{ github.workspace }}/build/gstlearn_dir

jobs:

  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v6

    - name: Install the customized SWIG from source
      uses: fabien-ors/install-swig-windows-action@v3
      with:
        swig-root: ${{env.SWIG_ROOT}}
        generator: "Visual Studio 18 2026"

    - name: Setup R
      uses: ./.github/actions/setup_r
      with:
        r-version: ${{env.R_VERSION}}

    - name: Install dependencies
      run: |
        pacman -Syu --noconfirm
        pacman -Sy --noconfirm mingw-w64-x86_64-boost
        pacman -Sy --noconfirm mingw-w64-x86_64-eigen3
        pacman -Sy --noconfirm mingw-w64-x86_64-nlopt
        pacman -Sy --noconfirm mingw-w64-x86_64-hdf5

    - name: Configure build directory
      run: |
        cmake `
          -B${{ env.BUILD_DIR }} `
          -DCMAKE_COMPILE_WARNING_AS_ERROR=ON `
          -DBUILD_TESTING=ON `
          -DBUILD_R=ON `
          -DBUILD_PYTHON=OFF `
          -DHDF5_USE_STATIC_LIBRARIES=ON `
          -DSWIG_EXECUTABLE=${{env.SWIG_ROOT}}/bin/swig

    - name: Build the package
      run: |
        cmake --build ${{env.BUILD_DIR}} --parallel 3

    - name: Install packages and execute non-regression tests
      run: |
        cmake --build ${{env.BUILD_DIR}} --parallel 3 --target check

    - name: Compress and upload artifacts
      if: always()
      uses: ./.github/actions/compress_and_upload_nonreg_artifacts
      with:
        os-name: rtools
