name: nonreg-tests_windows-latest-rtools

on:
  # Permit calling trigger
  workflow_call:
  # Activate the workflow at each push on dev branch
  #push:
  #  branches: [ dev ]
  # Activate the workflow at each pull request on dev branch
  #pull_request:
  #  branches: [ dev ]
  # Permit manual trigger
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Manual'
        required: false
        default: ''

env:
  # Customize the CMake build type here (Release, Debug)
  BUILD_TYPE: Release
  BUILD_DIR : build
  GENERATOR : "MSYS Makefiles"
  R_VERSION : "4.3.2"
  SWIG_ROOT : ${{github.workspace}}\swig_420b
  BOOST_ROOT: ${{github.workspace}}\boost
  BOOST_VERSION: "1.72.0"
  EIGEN_ROOT : ${{github.workspace}}\eigen
  EIGEN_VERSION : "3.4.0"

jobs:
  
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup R Version
      uses: r-lib/actions/setup-r@v2
      with:
        r-version: ${{env.R_VERSION}}

    - name: Install the customized SWIG from source under windows
      uses: fabien-ors/install-swig-windows-action@v2
      with:
        swig-root: ${{env.SWIG_ROOT}}
        generator: "Visual Studio 17 2022"
#
# Boost and Eigen already provided by Rtools
#
    - name: Install the Boost headers
      uses: ./.github/workflows/install-boost-windows
      with:
        boost-root: ${{env.BOOST_ROOT}}
        boost-version: ${{env.BOOST_VERSION}}

    - name: Install the Eigen headers
      uses: ./.github/workflows/install-eigen-windows
      with:
        eigen-root: ${{env.EIGEN_ROOT}}
        eigen-version: ${{env.EIGEN_VERSION}}
        
    - name: Configure CMake
      run: cmake -B${{env.BUILD_DIR}} -G "${{env.GENERATOR}}" -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DBUILD_R=ON -DBUILD_PYTHON=OFF -DBUILD_DOXYGEN=OFF -DUSE_HDF5=OFF -DSWIG_EXECUTABLE=${{env.SWIG_ROOT}}/bin/swig

    - name: Compile, install packages and execute non-regression tests
      run: cmake --build ${{env.BUILD_DIR}} --target check
