name: publish_python_macos

on:
  # Permit calling the workflow from outside (https://github.com/actions/runner/discussions/1884)
  workflow_call:
    inputs:
      dry_publish:
        description: 'Dry publish (no upload)'
        type: boolean
        required: false
        default: true
  # Permit manual trigger
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Manual'
        required: false
        default: ''
      dry_publish:
        description: 'Dry publish (no upload)'
        type: boolean
        required: false
        default: false

env:
  CMAKE_BUILD_TYPE : Release
  BUILD_DIR : build

jobs:
  build:
    runs-on: ${{matrix.arch.os}}
    strategy:
      matrix:
        # Python version
        python: [
          # Double quote for version is needed otherwise 3.10 => 3.1
            {py: "3.10"},
          ]
        # Only one arm64 and one x86_64 Mac OS version are needed
        arch: [
            {ar: x86_64, os: macos-15-intel, pat: /usr/local},
            {ar: arm64,  os: macos-14, pat: /opt/homebrew},
          ]

    steps:
    - uses: actions/checkout@v6

    - name: Install dependencies
      run: |
        brew install swig
        brew install --formula doxygen
        brew install llvm
        brew install boost
        brew install eigen

    - name: Setup uv
      uses: astral-sh/setup-uv@v8.1.0
      with:
        python-version: ${{ matrix.python.py }}
        activate-environment: true

    - name: Install Python dependencies
      run: |
        uv pip install numpy
        uv pip install myst-parser
        uv pip install sphinx
        uv pip install sphinx_rtd_theme
        uv pip install sphinx-cmake

    - name: Build & install NLopt static libraries
      uses: ./.github/actions/nlopt_static_unix

    - name: Build & install HDF5 static libraries
      uses: ./.github/actions/hdf5_static_unix

    - name : Configure build directory
      run : |
        cmake \
          -B${{ env.BUILD_DIR }} \
          -DCMAKE_COMPILE_WARNING_AS_ERROR=ON \
          -DHDF5_USE_STATIC_LIBRARIES=ON \
          -DBUILD_PYTHON=ON \
          -DBUILD_R=OFF \
          -DBUILD_DOC=ON
      env:
        CC: ${{matrix.arch.pat}}/opt/llvm/bin/clang
        CXX: ${{matrix.arch.pat}}/opt/llvm/bin/clang++

    - name : Build the package
      run : |
        cmake --build ${{env.BUILD_DIR}} --parallel 3 --target python_build

    - name : Create Wheel
      run : |
        cd ${{env.BUILD_DIR}}/python/${{env.CMAKE_BUILD_TYPE}}
        cp ${{matrix.arch.pat}}/opt/llvm/lib/libomp.dylib gstlearn
        install_name_tool -change ${{matrix.arch.pat}}/opt/llvm/lib/libomp.dylib @loader_path/libomp.dylib gstlearn/_gstlearn.so
        # Note: wheel must be declared not pure (see setup.py)
        uv build --wheel
        uvx wheel tags --python-tag=cp310 --abi-tag=abi3 dist/*.whl
        rm dist/*cp310-cp310*.whl
        if [ "${{matrix.arch.os}}" == "macos-15-intel" ] && [ $(ls dist/*universal2.whl | wc -l) -gt 0 ]; then
          # Fix wheel platform tag for x86_64 macOS
          WHEEL_FILE=$(ls dist/*universal2.whl)
          NEW_WHEEL_FILE=$(echo $WHEEL_FILE | sed 's/universal2/x86_64/')
          mv $WHEEL_FILE $NEW_WHEEL_FILE
        fi
        cd ../../..
        echo "MY_PKG=$(ls ${{env.BUILD_DIR}}/python/${{env.CMAKE_BUILD_TYPE}}/dist/*)" >> "$GITHUB_ENV"

    - uses: actions/upload-artifact@v6
      # Use specific artifact identifier for publishing all versions
      with:
        name: macos-python-package-${{matrix.arch.os}}
        path: ${{env.MY_PKG}}

  test:
    needs: build
    runs-on: ${{matrix.arch.os}}
    strategy:
      matrix:
        python: [
        # Double quote for version is needed otherwise 3.10 => 3.1
            {py: "3.10"},
            {py: "3.11"},
            {py: "3.12"},
            {py: "3.13"},
            {py: "3.14"}
          ]
        # Only one arm64 and one x86_64 Mac OS version are needed
        arch: [
            {ar: x86_64, os: macos-15-intel},
            {ar: arm64,  os: macos-14},
          ]

    steps:
    - uses: actions/checkout@v6

    - uses: actions/download-artifact@v7
      with:
        name: macos-python-package-${{matrix.arch.os}}

    - name: Setup uv
      uses: astral-sh/setup-uv@v8.1.0
      with:
        python-version: ${{ matrix.python.py }}
        activate-environment: true

    - name: Install Python package
      run: |
        uv pip install "./$(ls *.whl)[conv]"

    - name: Test installed Python package
      uses: ./.github/actions/run_python_tests

  publish:
    needs: test
    if: ${{inputs.dry_publish == false}}

    # Only ubuntu can upload via ssh
    runs-on: ubuntu-latest

    steps:
    # Upload packages to pypi
    - uses: fabien-ors/pypi-publish-action@v4
      with:
        repo: pypi
        username: __token__
        password: ${{secrets.TWINE_PYPI_PWD}}
        pattern: macos-python-package-*

    # Delete the artifacts (for freeing storage space under github)
    - uses: geekyeggo/delete-artifact@v5
      with:
        name: macos-python-package
