name: publish_r_macos

on:
  # Permit calling the workflow from outside (https://github.com/actions/runner/discussions/1884)
  workflow_call:
    inputs:
      dry_publish:
        description: 'Dry publish (no upload)'
        type: boolean
        required: false
        default: true
  # Permit manual trigger
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Manual'
        required: false
        default: ''
      dry_publish:
        description: 'Dry publish (no upload)'
        type: boolean
        required: false
        default: false

env:
  CMAKE_BUILD_TYPE : Release
  BUILD_DIR : build
  SWIG_ROOT : ${{github.workspace}}/swig_420b

jobs:
  build:
    runs-on: ${{matrix.arch.os}}
    strategy:
      matrix:
        # Last releases from here https://cran.r-project.org/src/base/R-4/
        r_version: [4.0.5, 4.1.3, 4.2.3, 4.3.3, 4.4.2]
        arch: [
            {ar: x86_64, os: macos-13, pat: /usr/local},
            {ar: arm64,  os: macos-14, pat: /opt/homebrew},
            {ar: arm64,  os: macos-15, pat: /opt/homebrew}
         ]
        exclude:
          - arch: {os: macos-14}
            r_version: 4.0.5
          - arch: {os: macos-15}
            r_version: 4.0.5

    steps:
    - uses: actions/checkout@v4

    - name : Install dependencies
      run: |
        brew install --formula doxygen
        brew install llvm
        brew install boost
        brew install eigen

    # https://github.com/r-lib/actions/issues/948
    - name: Uninstall pkgconfig due to setup-R error
      if: ${{ vars.RUNNER == 'macos-14' }}
      run: |
        brew uninstall pkg-config@0.29.2

    - name: Setup R Version
      uses: r-lib/actions/setup-r@v2
      with:
        r-version: ${{matrix.r_version}}

    - name: Install roxygen2
      uses: r-lib/actions/setup-r-dependencies@v2
      with:
        packages: roxygen2, pkgbuild
        install-pandoc: false

    - name: Install the customized SWIG from source
      uses: fabien-ors/install-swig-unix-action@v1
      with:
        swig-root: ${{env.SWIG_ROOT}}
        generator: "Unix Makefiles"

    - name: Build & install NLopt static libraries
      uses: ./.github/actions/nlopt_static_unix

    - name : Configure build directory
      run : |
        cmake \
          -B${{ env.BUILD_DIR }} \
          -DBUILD_PYTHON=OFF \
          -DBUILD_R=ON \
          -DBUILD_DOXYGEN=ON \
          -DSWIG_EXECUTABLE=${{env.SWIG_ROOT}}/bin/swig
      env:
        CC: ${{matrix.arch.pat}}/opt/llvm/bin/clang
        CXX: ${{matrix.arch.pat}}/opt/llvm/bin/clang++

    - name : Build the package and save generated file name in the environment
      run : |
        cmake --build ${{env.BUILD_DIR}} --parallel 3 --target r_install
        echo "MY_PKG=$(ls ${{env.BUILD_DIR}}/r/${{env.CMAKE_BUILD_TYPE}}/gstlearn_*.tgz)" >> "$GITHUB_ENV"

    - uses: actions/upload-artifact@v4
      # Use specific artifact identifier for publishing all versions
      with:
        name: macos-r-package-${{matrix.arch.os}}-${{matrix.r_version}}
        path: ${{env.MY_PKG}}

  test:
    needs: build
    runs-on: ${{matrix.arch.os}}
    strategy:
      matrix:
        # Last releases from here https://cran.r-project.org/src/base/R-4/
        r_version: [4.0.5, 4.1.3, 4.2.3, 4.3.3, 4.4.2]
        arch: [
            {ar: x86_64, os: macos-13, pat: /usr/local},
            {ar: arm64,  os: macos-14, pat: /opt/homebrew},
            {ar: arm64,  os: macos-15, pat: /opt/homebrew}
         ]
        exclude:
          - arch: {os: macos-14}
            r_version: 4.0.5
          - arch: {os: macos-15}
            r_version: 4.0.5

    steps:
    - uses: actions/checkout@v4

    - uses: actions/download-artifact@v4
      with:
        name: macos-r-package-${{matrix.arch.os}}-${{matrix.r_version}}

    # https://github.com/r-lib/actions/issues/948
    - name: Uninstall pkgconfig due to setup-R error
      if: ${{ vars.RUNNER == 'macos-14' }}
      run: |
        brew uninstall pkg-config@0.29.2

    - name: Setup R Version
      uses: r-lib/actions/setup-r@v2
      with:
        r-version: ${{matrix.r_version}}

    - name: Install macOS dependencies
      run: brew install llvm

    - name: Install gstlearn R package
      run: Rscript -e "install.packages(\"$(ls *.tgz)\", repos=NULL, type='source')"

    - name: Test installed R package
      run: |
        Rscript -e "library('gstlearn'); acknowledge_gstlearn()"
        Rscript tests/r/test_Arguments.R
        Rscript tests/r/test_Assessors.R
        Rscript tests/r/test_Matrix.R

  publish:
    needs: test
    if: ${{inputs.dry_publish == false}}

    # Only ubuntu can upload via ssh
    runs-on: ubuntu-latest

    steps:
    - uses: fabien-ors/cran-publish-action@v4
      with:
        host: ${{secrets.CG_HOST}}
        username: ${{secrets.CG_USR}}
        password: ${{secrets.CG_PWD}}
        repo-path: "/var/www/html/cran"

    # Delete the artifacts (for freeing storage space under github)
    - uses: geekyeggo/delete-artifact@v5
      with:
        name: macos-r-package-*
