name: publish_doxygen

on:
  # Permit calling the workflow from outside (https://github.com/actions/runner/discussions/1884)
  workflow_call:
    inputs:
      dry_publish:
        description: 'Dry publish (no upload)'
        type: boolean
        required: false
        default: true
  # Permit manual trigger
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Manual'
        required: false
        default: ''
      dry_publish:
        description: 'Dry publish (no upload)'
        type: boolean
        required: false
        default: false

env:
  BUILD_TYPE: Release
  BUILD_DIR : build

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      # https://docs.github.com/en/actions/using-jobs/defining-outputs-for-jobs
      project_version: ${{ steps.main_step.outputs.PROJECT_VERSION }}

    steps:
    - uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        sudo rm /etc/apt/sources.list.d/microsoft-prod.list
        sudo apt-get update
        sudo apt-get install -yq \
          libopenmpi-dev \
          libboost-dev \
          libeigen3-dev \
          doxygen

    - name: Build doxygen documentation and save generated folder name in the environment
      id: main_step
      run: |
        cmake -B${{env.BUILD_DIR}} -DBUILD_DOXYGEN=ON -DBUILD_PYTHON=OFF -DBUILD_R=OFF
        cmake --build ${{env.BUILD_DIR}} --target doxygen
        PROJECT_VERSION=$(cmake --build ${{env.BUILD_DIR}} --target print_version | grep PROJECT_VERSION | cut -d "=" -f2 | xargs)
        echo "HTML_FOLDER=${{env.BUILD_DIR}}/doxygen/html" >> "$GITHUB_ENV"
        echo "PROJECT_VERSION=${PROJECT_VERSION}" >> "$GITHUB_OUTPUT"

    - uses: actions/upload-artifact@v3
      with:
        # This will become the folder name in the server
        name: doxygen
        path: ${{ env.HTML_FOLDER }}

  publish:
    needs: build
    if: ${{inputs.dry_publish == false}}
    
    # Only ubuntu can upload to a server easily (ssh)
    runs-on: ubuntu-latest
    
    steps:
      - env:
          PROJECT_VERSION: ${{needs.build.outputs.project_version}}
        uses: fabien-ors/folder-publish-action@v1
        with:
          host: ${{ secrets.CG_HOST }}
          username: ${{ secrets.CG_USR }}
          password: ${{ secrets.CG_PWD }}
          dest-path: "/var/www/html/gstlearn/${{ env.PROJECT_VERSION }}"
  
      # Delete the artifacts (for freeing storage space under github)
      - uses: geekyeggo/delete-artifact@v2
        with:
          name: doxygen
