name: publish_r_windows

on:
  # Permit calling the workflow from outside (https://github.com/actions/runner/discussions/1884)
  workflow_call:
    inputs:
      dry_publish:
        description: 'Dry publish (no upload)'
        type: boolean
        required: false
        default: true
  # Permit manual trigger
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Manual'
        required: false
        default: ''
      dry_publish:
        description: 'Dry publish (no upload)'
        type: boolean
        required: false
        default: false

env:
  # Customize the CMake build type here (Release, Debug)
  CMAKE_BUILD_TYPE : Release
  BUILD_DIR : build
  CMAKE_GENERATOR : "MSYS Makefiles"
  SWIG_ROOT : ${{github.workspace}}\swig
  DOXYGEN_ROOT : ${{github.workspace}}\doxygen
  DOXYGEN_VERSION : "1.9.8"
  CMAKE_TOOLCHAIN_FILE : C:\vcpkg\scripts\buildsystems\vcpkg.cmake
  VCPKG_LIBRARY_LINKAGE: static

jobs:

  build:
    runs-on: windows-2022
    outputs:
      # https://docs.github.com/en/actions/using-jobs/defining-outputs-for-jobs
      cran_path: ${{ steps.define_cran_path.outputs.CRAN_PATH }}
    strategy:
      matrix:
        # Last releases from here https://cran.r-project.org/src/base/R-4/
        r_version: [4.2.3, 4.3.3, 4.4.3, 4.5.2]

    steps:
    - uses: actions/checkout@v6

    - name: Setup R Version
      uses: r-lib/actions/setup-r@v2
      with:
        r-version: ${{matrix.r_version}}

    # In R 4.2 ggplot2 & ggpubr prefer older Matrix version
    - name: Install R Matrix dependency
      run: Rscript -e "install.packages ('https://cran.r-project.org/src/contrib/Archive/Matrix/Matrix_1.6-5.tar.gz')"

    - name: Install R dependencies (binary)
      run: Rscript -e "install.packages (c('ggplot2', 'ggpubr', 'ggnewscale', 'roxygen2', 'pkgbuild'), type='binary')"

    - name: Fix CMake Path (system prefered to rtools)
      run: |
        $cmakePath = (Get-Command cmake.exe -TotalCount 2 | Select-Object -ExpandProperty Source | Where-Object { $_ -notlike "*rtools*" } | Select-Object -First 1)
        if ($cmakePath) {
          $cmakeDir = Split-Path $cmakePath
          echo "$cmakeDir" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
        }
      shell: powershell

    - name: Install dependencies
      run: |
        pacman -Syu --noconfirm
        pacman -Sy --noconfirm mingw-w64-x86_64-boost
        pacman -Sy --noconfirm mingw-w64-x86_64-eigen3

    - name: Install Doxygen under windows
      uses: fabien-ors/install-doxygen-windows-action@v1
      with:
        doxygen-root: ${{env.DOXYGEN_ROOT}}
        doxygen-version: ${{env.DOXYGEN_VERSION}}

    - name: Install the customized SWIG from source
      uses: fabien-ors/install-swig-windows-action@v3
      with:
        swig-root: ${{env.SWIG_ROOT}}
        generator: "Visual Studio 17 2022"

    - name: Build & install nlopt static libraries
      uses: ./.github/actions/nlopt_static_windows

    - name: Build & install HDF5 static libraries
      uses: ./.github/actions/hdf5_static_windows

    - name : Configure build directory
      run : |
        cmake `
          -B${{ env.BUILD_DIR }} `
          -DCMAKE_COMPILE_WARNING_AS_ERROR=ON `
          -DBUILD_PYTHON=OFF `
          -DBUILD_R=ON `
          -DHDF5_USE_STATIC_LIBRARIES=ON `
          -DSWIG_EXECUTABLE=${{env.SWIG_ROOT}}/bin/swig `
          -DBUILD_DOC=ON `
          -DDoxygen_ROOT=${{env.DOXYGEN_ROOT}}
      env:
        HDF5_ROOT: "C:/Program Files/HDF5/cmake/"

    - name : Build the package and save generated file name in the environment
      run : |
        cmake --build ${{env.BUILD_DIR}} --parallel 3 --target r_install
        $PKG_PATH = Get-ChildItem -Path "${{env.BUILD_DIR}}/r/${{env.CMAKE_BUILD_TYPE}}/gstlearn_*.zip" -File
        echo "MY_PKG=$PKG_PATH" | Out-File -FilePath $Env:GITHUB_ENV -Encoding utf8 -Append

    - name: Define the CRAN path on our server
      id: define_cran_path
      shell: powershell
      run: |
        $versionOutput = cmake --build ${{env.BUILD_DIR}} --target print_version
        $projectVersion = $versionOutput | Select-String "PROJECT_VERSION" | ForEach-Object {($_ -split "=")[1].Trim()}
        $projectFullVersion = $versionOutput | Select-String "PROJECT_FULL_VERSION" | ForEach-Object {($_ -split "=")[1].Trim()}
        if ($projectVersion -eq $projectFullVersion) {
            $cranPath = "/var/www/html/cran"
        } else {
            $cranPath = "/var/www/html/cran/prerelease"
        }
        "CRAN_PATH=$cranPath" | Out-File -FilePath $env:GITHUB_OUTPUT -Encoding utf8 -Append

    - name : Always show r_doc log
      if: success() || failure()
      run: |
        cat ${{env.BUILD_DIR}}/r/${{env.CMAKE_BUILD_TYPE}}/create_doc.out

    - uses: actions/upload-artifact@v6
      # Use specific artifact identifier for publishing all R versions
      with:
        name: windows-r-package-${{matrix.r_version}}
        path: ${{env.MY_PKG}}

  test:
    needs: build
    runs-on: windows-2022
    strategy:
      matrix:
        # Last releases from here https://cran.r-project.org/src/base/R-4/
        r_version: [4.2.3, 4.3.3, 4.4.3, 4.5.2]

    steps:
    - uses: actions/checkout@v6

    - uses: actions/download-artifact@v7
      with:
        name: windows-r-package-${{matrix.r_version}}

    - name: Setup R Version
      uses: r-lib/actions/setup-r@v2
      with:
        r-version: ${{matrix.r_version}}

    # In R 4.2 ggplot2 & ggpubr prefer older Matrix version
    - name: Install R Matrix dependency
      run: Rscript -e "install.packages ('https://cran.r-project.org/src/contrib/Archive/Matrix/Matrix_1.6-5.tar.gz')"

    - name: Install R dependencies (binary)
      run: Rscript -e "install.packages (c('ggplot2', 'ggpubr', 'ggnewscale', 'roxygen2', 'pkgbuild'), type='binary')"

    - name: Install R package
      run: Rscript -e "install.packages(""'""./$(ls *.zip)""'"", repos=NULL, type='source')"
      shell: bash

    - name: Test installed R package
      uses: ./.github/actions/run_r_tests

  publish:
    needs: test
    if: ${{inputs.dry_publish == false}}

    # Only ubuntu can upload to CRAN easily (ssh)
    runs-on: ubuntu-latest

    steps:
      # Publish packages to our CRAN
      - env:
          CRAN_PATH: ${{needs.build.outputs.cran_path}}
        uses: fabien-ors/cran-publish-action@v4
        with:
          host: ${{secrets.CG_HOST}}
          username: ${{secrets.CG_USR}}
          password: ${{secrets.CG_PWD}}
          repo-path: ${{env.CRAN_PATH}}

        # Delete the artifacts (for freeing storage space under github)
      - uses: geekyeggo/delete-artifact@v5
        with:
          name: windows-r-package-*
