name: publish_python_ubuntu-latest

on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Manual'
        required: false
        default: ''

env:
  BUILD_TYPE: Release
  BUILD_DIR : build
  BUILD_PLAT: manylinux1_x86_64

jobs:
  build:
    runs-on: ubuntu-latest
    strategy :
      matrix:
       python: ["3.8","3.9","3.10","3.11"]

    steps:
    - uses: actions/checkout@v3

    - name: Setup Python Version
      uses: actions/setup-python@v4
      with:
        python-version: ${{matrix.python}}

    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install -yq libboost-all-dev libhdf5-dev

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install numpy==1.20.3 twine wheel pybind11 pandas

    - name : Create Wheels
      run : |
        cmake -B${{env.BUILD_DIR}} -DCMAKE_BUILD_TYPE:STRING=${{env.BUILD_TYPE}} -DBUILD_PYTHON=ON
        cmake --build ${{env.BUILD_DIR}} --target python_build -- -j 3
        cd ${{env.BUILD_DIR}}/python/${{env.BUILD_TYPE}}
        # Note: wheel must be declared pure (see setup.py)
        python setup.py bdist_wheel --plat-name=${{env.BUILD_PLAT}}

    - name : Upload
      run : python -m twine upload ${{env.BUILD_DIR}}/python/${{env.BUILD_TYPE}}/dist/*
      env:
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: ${{secrets.TWINE_TEST_TOKEN}}
        TWINE_REPOSITORY: testpypi

