name: publish_python_ubuntu

on:
  # Permit calling the workflow from outside (https://github.com/actions/runner/discussions/1884)
  workflow_call:
    inputs:
      dry_publish:
        description: 'Dry publish (no upload)'
        type: boolean
        required: false
        default: true
  # Permit manual trigger
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Manual'
        required: false
        default: ''
      dry_publish:
        description: 'Dry publish (no upload)'
        type: boolean
        required: false
        default: false

env:
  CMAKE_BUILD_TYPE : Release
  BUILD_DIR : build
  BUILD_PLAT : manylinux1_x86_64

jobs:
  build:
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        # Python version + Numpy version
        python: [
          # Double quote for version is needed otherwise 3.10 => 3.1
            {py: "3.9"},
            {py: "3.10"},
            {py: "3.11"},
            {py: "3.12"},
            {py: "3.13"}
          ]
        # Only one "old"" Linux and a generic platform name BUILD_PLAT
        os: [ubuntu-22.04]

    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo rm /etc/apt/sources.list.d/microsoft-prod.list
        sudo apt-get update
        sudo apt-get install -yq \
          swig \
          doxygen \
          libhdf5-dev \
          libopenmpi-dev \
          libboost-dev \
          libeigen3-dev

    - name: Setup Python Version
      uses: actions/setup-python@v5
      with:
        python-version: ${{matrix.python.py}}

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install numpy
        python -m pip install build

    - name : Configure build directory
      run : |
        cmake \
          -B${{ env.BUILD_DIR }} \
          -DBUILD_PYTHON=ON \
          -DBUILD_R=OFF \
          -DBUILD_DOXYGEN=ON

    - name : Build the package
      run : |
        cmake --build ${{env.BUILD_DIR}} --parallel 3 --target python_build

    - name : Create Wheel
      run : |
        cd ${{env.BUILD_DIR}}/python/${{env.CMAKE_BUILD_TYPE}}
        # Note: wheel must be declared not pure (see setup.py)
        python -m build --wheel -C="--build-option=--plat-name=${{env.BUILD_PLAT}}"
        cd ../../..
        echo "MY_PKG=$(ls ${{env.BUILD_DIR}}/python/${{env.CMAKE_BUILD_TYPE}}/dist/*)" >> "$GITHUB_ENV"

    - uses: actions/upload-artifact@v4
      # Use specific artifact identifier for publishing all versions
      with:
        name: ubuntu-python-package-${{matrix.os}}-${{matrix.python.py}}
        path: ${{env.MY_PKG}}

  publish:
    needs: build
    if: ${{inputs.dry_publish == false}}

    # Only ubuntu can upload via ssh
    runs-on: ubuntu-latest

    steps:
    - uses: fabien-ors/pypi-publish-action@v2
      with:
        repo: pypi
        username: __token__
        password: ${{secrets.TWINE_PYPI_PWD}}
        pattern: ubuntu-python-package-*

    # Delete the artifacts (for freeing storage space under github)
    - uses: geekyeggo/delete-artifact@v5
      with:
        name: ubuntu-python-package-*

