name: install-boost-unix
description: "Install the Boost headers under Linux/MacOS"
author: 'Fabien Ors'

inputs:
  boost-root:
    description: 'Boost installation directory'
  boost-version:
    description: 'Boost version to be installed'
    default: "1.72.0"

runs:
  using: "composite"
  steps:
  
  - name : Download and uncompressed Boost headers
    shell: bash
    run: |
      BOOST_VERSION=$(echo ${{inputs.boost-version}} | sed s/\\./_/g)
      BOOST_URL="https://netix.dl.sourceforge.net/project/boost/boost/${{inputs.boost-version}}/boost_$BOOST_VERSION.tar.bz2"
      mkdir ${{inputs.boost-root}}
      curl --progress-bar --location --output ${{inputs.boost-root}}/download.tar.bz2 $BOOST_URL
      7z -o${{inputs.boost-root}} x ${{inputs.boost-root}}/download.tar.bz2 -y -bd
      7z -o${{inputs.boost-root}} x ${{inputs.boost-root}}/download.tar -y -bd
